import fs from 'fs';
import path from 'path';

export interface MaritimeWordEntry {
  id: number;
  word: string;
  partOfSpeech: string;
  meaning: string[];
  englishDefinition: string;
  difficulty: 'low' | 'medium' | 'high';
  topic: 'navigation' | 'emergency' | 'safety' | 'cargo' | 'communication' | 'engine';
}

// Phase 3: 국제해사협약 (COLREGs, SOLAS, MARPOL, STCW, ISM Code) 및 선박 실무 핵심 어휘
export const conventionsAndPracticeWords: Array<Omit<MaritimeWordEntry, 'id'>> = [
  // --- 1. COLREGs (국제해상충돌예방규칙) 핵심 용어 ---
  {
    word: 'risk of collision',
    partOfSpeech: '명사',
    meaning: ['충돌의 위험'],
    englishDefinition: 'A dangerous situation deemed to exist if the compass bearing of an approaching vessel does not appreciably change.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'proper lookout',
    partOfSpeech: '명사',
    meaning: ['적절한 경계'],
    englishDefinition: 'Maintaining continuous visual and auditory surveillance by all available means as required by COLREGs Rule 5.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'vessel not under command',
    partOfSpeech: '명사',
    meaning: ['조종불능선', 'NUC'],
    englishDefinition: 'A vessel which through some exceptional circumstance is unable to maneuver as required by the rules.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'vessel restricted in her ability to maneuver',
    partOfSpeech: '명사',
    meaning: ['조종제한선', 'RAM'],
    englishDefinition: 'A vessel which from the nature of her work is restricted in her ability to maneuver as required by the collision regulations.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'overtaking vessel',
    partOfSpeech: '명사',
    meaning: ['추월선'],
    englishDefinition: 'A vessel coming up with another vessel from a direction more than 22.5 degrees abaft her beam.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'head-on situation',
    partOfSpeech: '명사',
    meaning: ['마주치는 상태', '정면 반대침로 마주침'],
    englishDefinition: 'A situation where two power-driven vessels are meeting on reciprocal or nearly reciprocal courses so as to involve risk of collision.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'crossing situation',
    partOfSpeech: '명사',
    meaning: ['횡단 상태'],
    englishDefinition: 'A situation where two power-driven vessels are crossing so as to involve risk of collision, requiring the one having the other on starboard to keep clear.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'action to avoid collision',
    partOfSpeech: '명사',
    meaning: ['충돌 회피 동작'],
    englishDefinition: 'Any positive maneuver made in ample time and with due regard to the observance of good seamanship to avert collision.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'traffic separation scheme',
    partOfSpeech: '명사',
    meaning: ['통항분리수역', 'TSS'],
    englishDefinition: 'A designated maritime traffic routing system aimed at regulating the flow of converging traffic in congested waters.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'inshore traffic zone',
    partOfSpeech: '명사',
    meaning: ['연안통항대'],
    englishDefinition: 'A designated routing area between the landward boundary of a TSS and the adjacent coast designated for local coastal traffic.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'separation zone',
    partOfSpeech: '명사',
    meaning: ['분리대', '통항분리선'],
    englishDefinition: 'A zone or line separating lanes in which vessels are proceeding in opposite or nearly opposite directions.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'narrow channel',
    partOfSpeech: '명사',
    meaning: ['협수로'],
    englishDefinition: 'A restricted waterway where vessels navigating must keep as near to the outer limit on their starboard side as is safe.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'masthead light',
    partOfSpeech: '명사',
    meaning: ['마스트등', '전조등'],
    englishDefinition: 'A white navigation light placed over the fore-and-aft centerline showing an unbroken light over an arc of 225 degrees.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'sidelights',
    partOfSpeech: '명사',
    meaning: ['현등', '홍현등 및 녹현등'],
    englishDefinition: 'A green light on the starboard side and a red light on the port side, each showing an unbroken light over an arc of 112.5 degrees.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'sternlight',
    partOfSpeech: '명사',
    meaning: ['선미등'],
    englishDefinition: 'A white light placed nearly as practicable at the stern showing an unbroken arc of 135 degrees aft.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'towing light',
    partOfSpeech: '명사',
    meaning: ['예인등'],
    englishDefinition: 'A yellow light having the same characteristics as the sternlight, exhibited by a vessel engaged in towing.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'all-round light',
    partOfSpeech: '명사',
    meaning: ['전주등'],
    englishDefinition: 'A navigation light showing an uninterrupted light over a complete horizontal horizon arc of 360 degrees.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'flashing light',
    partOfSpeech: '명사',
    meaning: ['섬광등'],
    englishDefinition: 'A light flashing at regular intervals at a frequency of 120 flashes or more per minute.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'prolonged blast',
    partOfSpeech: '명사',
    meaning: ['장음', '장음 기적 신호'],
    englishDefinition: 'A blast of four to six seconds duration given on a ship whistle.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'short blast',
    partOfSpeech: '명사',
    meaning: ['단음', '단음 기적 신호'],
    englishDefinition: 'A blast of about one second duration given on a ship whistle.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'bell',
    partOfSpeech: '명사',
    meaning: ['호종', '선박 종'],
    englishDefinition: 'A mandatory acoustic signalling apparatus rung rapidly in restricted visibility while anchored.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'gong',
    partOfSpeech: '명사',
    meaning: ['호공', '징'],
    englishDefinition: 'A percussion sound signaling device sounded in the after part of a vessel over 100 meters in length during fog.',
    difficulty: 'medium',
    topic: 'communication',
  },
  {
    word: 'sound signal',
    partOfSpeech: '명사',
    meaning: ['음향 신호'],
    englishDefinition: 'Acoustic warnings sounded by whistle, bell, or gong to indicate vessel maneuvers or presence in fog.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'distress signal',
    partOfSpeech: '명사',
    meaning: ['조난 신호'],
    englishDefinition: 'Recognized international visual, acoustic, or radio signals indicating that a vessel is in grave and imminent danger.',
    difficulty: 'low',
    topic: 'emergency',
  },

  // --- 2. SOLAS (해상인명안전협약) 구명·소방 설비 ---
  {
    word: 'life-saving appliances',
    partOfSpeech: '명사',
    meaning: ['구명 설비', 'LSA'],
    englishDefinition: 'Equipment designed to safeguard crew and passengers in emergency evacuation and abandonment situations.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'fire-fighting appliances',
    partOfSpeech: '명사',
    meaning: ['소방 설비', 'FFA'],
    englishDefinition: 'Apparatus and systems installed onboard to detect, control, and extinguish shipboard fires.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'totally enclosed lifeboat',
    partOfSpeech: '명사',
    meaning: ['전폐형 구명정'],
    englishDefinition: 'A rigid watertight covered lifeboat that provides full protection against toxic fumes, heavy seas, and fire.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'free-fall lifeboat',
    partOfSpeech: '명사',
    meaning: ['자유강하식 구명정'],
    englishDefinition: 'A specialized lifeboat launched by sliding down an inclined ramp and free-falling directly into the sea.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'hydrostatic release unit',
    partOfSpeech: '명사',
    meaning: ['수압해제장치', 'HRU'],
    englishDefinition: 'An automatic pressure-activated release mechanism that frees a liferaft when submerged to 1.5 to 4 meters.',
    difficulty: 'high',
    topic: 'safety',
  },
  {
    word: 'immersion suit',
    partOfSpeech: '명사',
    meaning: ['방수복', '침수복'],
    englishDefinition: 'A thermal protective watertight suit designed to prevent hypothermia when floating in freezing seawater.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'thermal protective aid',
    partOfSpeech: '명사',
    meaning: ['보온구', 'TPA'],
    englishDefinition: 'A waterproof metallic bag or suit worn over a lifejacket to reduce the conductive body heat loss of a survivor.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'line-throwing appliance',
    partOfSpeech: '명사',
    meaning: ['구명줄 발사기'],
    englishDefinition: 'A rocket-propelled device capable of throwing a line over 230 meters to establish connection between vessels.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'rocket parachute flare',
    partOfSpeech: '명사',
    meaning: ['낙하산부 신호탄'],
    englishDefinition: 'A pyrotechnic distress flare fired upward to at least 300 meters that drifts down slowly under a parachute burning bright red.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'hand flare',
    partOfSpeech: '명사',
    meaning: ['신호홍염'],
    englishDefinition: 'A handheld pyrotechnic distress signal burning with a bright red flame for at least one minute.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'buoyant smoke signal',
    partOfSpeech: '명사',
    meaning: ['발연신호', '부유식 연막신호'],
    englishDefinition: 'A floating pyrotechnic canister emitting highly visible dense orange smoke for daytime rescue location.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'international shore connection',
    partOfSpeech: '명사',
    meaning: ['국제육상시설연결구'],
    englishDefinition: 'A standardized universal flange allowing a ship fire main to connect directly to shore fire-fighting water supplies.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'emergency fire pump',
    partOfSpeech: '명사',
    meaning: ['비상소화펌프'],
    englishDefinition: 'An independently powered auxiliary fire pump located outside the machinery space to supply water if the main engine room is lost.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'fire damper',
    partOfSpeech: '명사',
    meaning: ['방화 댐퍼', '화재 차단판'],
    englishDefinition: 'A heat-activated or remotely operated steel closure flap inside ventilation ducts to isolate fire compartments.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'self-contained breathing apparatus',
    partOfSpeech: '명사',
    meaning: ['공기호흡기', 'SCBA'],
    englishDefinition: 'A compressed-air breathing set worn by firefighters entering smoke-filled compartments.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'emergency escape breathing device',
    partOfSpeech: '명사',
    meaning: ['비상대피용 호흡구', 'EEBD'],
    englishDefinition: 'A short-duration (10-15 min) air supply device used exclusively for escape from hazardous atmospheres.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'inert gas system',
    partOfSpeech: '명사',
    meaning: ['불활성가스 장치', 'IGS'],
    englishDefinition: 'A system supplying oxygen-depleted gas (less than 5% O2) into oil cargo tanks to prevent flammable explosions.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'deck water seal',
    partOfSpeech: '명사',
    meaning: ['갑판 수봉기'],
    englishDefinition: 'A water-filled barrier preventing hydrocarbon gases from flowing back from cargo tanks into the machinery space.',
    difficulty: 'high',
    topic: 'safety',
  },
  {
    word: 'pressure vacuum relief valve',
    partOfSpeech: '명사',
    meaning: ['통기압력진공밸브', 'PV 밸브'],
    englishDefinition: 'A dual-action breather valve preventing excessive pressure buildup or dangerous vacuum formation in cargo oil tanks.',
    difficulty: 'high',
    topic: 'safety',
  },
  {
    word: 'voyage data recorder',
    partOfSpeech: '명사',
    meaning: ['항해자료기록기', 'VDR'],
    englishDefinition: 'A black box recording bridge audio, radar images, heading, speed, and rudder angle for casualty investigation.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'emergency towing arrangement',
    partOfSpeech: '명사',
    meaning: ['비상예인장치', 'ETA 설비'],
    englishDefinition: 'Pre-rigged heavy towing gear fitted forward and aft on tankers for rapid emergency salvage hookup.',
    difficulty: 'high',
    topic: 'safety',
  },

  // --- 3. MARPOL (해양오염방지협약) 관련 핵심 규약 ---
  {
    word: 'special area',
    partOfSpeech: '명사',
    meaning: ['특별수역'],
    englishDefinition: 'A sea area designated under MARPOL where mandatory strict discharge prohibitions apply due to oceanographical sensitivity.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'oil record book',
    partOfSpeech: '명사',
    meaning: ['유류기록부', 'ORB'],
    englishDefinition: 'A mandatory official log documenting all internal oil transfers, bunkering, and oily bilge discharges under MARPOL Annex I.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'shipboard oil pollution emergency plan',
    partOfSpeech: '명사',
    meaning: ['해양오염비상계획서', 'SOPEP'],
    englishDefinition: 'A formalized emergency response guide outlining operational procedures to mitigate accidental oil discharges.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'garbage management plan',
    partOfSpeech: '명사',
    meaning: ['선내 폐기물 관리계획'],
    englishDefinition: 'A written onboard procedure for collecting, storing, processing, and disposing of shipboard garbage under MARPOL Annex V.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'garbage record book',
    partOfSpeech: '명사',
    meaning: ['폐기물기록부'],
    englishDefinition: 'An official logbook recording each discharge operation to sea, shore reception facilities, or incineration.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'ballast water management',
    partOfSpeech: '명사',
    meaning: ['선박평형수 관리', 'BWM'],
    englishDefinition: 'Procedures and systems to prevent the transfer of harmful aquatic organisms and pathogens via ballast water discharge.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'sewage treatment plant',
    partOfSpeech: '명사',
    meaning: ['분뇨처리장치'],
    englishDefinition: 'A biological or chemical processing plant onboard that disinfects and aerates black water before lawful discharge.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'holding tank',
    partOfSpeech: '명사',
    meaning: ['오수 저장탱크'],
    englishDefinition: 'A dedicated containment tank holding untreated sewage or grey water until it can be discharged to shore facilities.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'comminuter',
    partOfSpeech: '명사',
    meaning: ['분쇄기'],
    englishDefinition: 'A motorized macerator that shreds solid food wastes or sewage into particles smaller than 25 mm before sea disposal.',
    difficulty: 'high',
    topic: 'engine',
  },
  {
    word: 'low sulfur fuel oil',
    partOfSpeech: '명사',
    meaning: ['저유황연료유', 'LSFO'],
    englishDefinition: 'Marine fuel containing 0.50% or less sulfur content complying with the global IMO 2020 sulfur cap.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'exhaust gas cleaning system',
    partOfSpeech: '명사',
    meaning: ['배기가스 세정장치', '스크러버'],
    englishDefinition: 'An exhaust scrubber that washes SOx emissions out of engine exhaust gases using seawater or alkaline chemicals.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'emission control area',
    partOfSpeech: '명사',
    meaning: ['배출규제해역', 'ECA'],
    englishDefinition: 'Sea areas where stringent fuel sulfur limits (0.10% sulfur) and NOx Tier III controls are enforced under MARPOL Annex VI.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'bunker delivery note',
    partOfSpeech: '명사',
    meaning: ['벙커 인도증', 'BDN'],
    englishDefinition: 'A legal document provided by the fuel supplier specifying the density, viscosity, and sulfur percentage of delivered bunkers.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'energy efficiency design index',
    partOfSpeech: '명사',
    meaning: ['에너지효율설계지수', 'EEDI'],
    englishDefinition: 'A regulatory metric measuring grams of CO2 emitted per transport work (ton-mile) for newly constructed ships.',
    difficulty: 'high',
    topic: 'safety',
  },
  {
    word: 'carbon intensity indicator',
    partOfSpeech: '명사',
    meaning: ['탄소집약도지수', 'CII'],
    englishDefinition: 'An operational energy efficiency rating (grades A to E) tracking the actual greenhouse gas emissions of in-service ships.',
    difficulty: 'high',
    topic: 'safety',
  },

  // --- 4. STCW 및 ISM Code (선원 훈련·자격 및 선박안전관리체제) ---
  {
    word: 'certificate of competency',
    partOfSpeech: '명사',
    meaning: ['해기사 면허증', '자격증명서 (CoC)'],
    englishDefinition: 'An official certificate issued by a maritime administration authorizing the holder to serve as a marine officer.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'hours of rest',
    partOfSpeech: '명사',
    meaning: ['법정 최소 휴식시간'],
    englishDefinition: 'Mandatory minimum rest periods (at least 10 hours in any 24-hour period) to prevent seafarer fatigue under STCW and MLC.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'watchkeeping arrangement',
    partOfSpeech: '명사',
    meaning: ['당직 배치 기준'],
    englishDefinition: 'The organizational schedule ensuring adequate rested officers and ratings are on navigational and engineering watch.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'designated person ashore',
    partOfSpeech: '명사',
    meaning: ['육상 안전관리책임자', 'DPA'],
    englishDefinition: 'A key shore-based coordinator providing direct access between the shipboard crew and highest shipping executive under the ISM Code.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'safety management manual',
    partOfSpeech: '명사',
    meaning: ['안전관리매뉴얼', 'SMM'],
    englishDefinition: 'The core documented procedural book detailing safety policies, operational checklists, and emergency guidelines onboard.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'non-conformity',
    partOfSpeech: '명사',
    meaning: ['부적합 사항'],
    englishDefinition: 'An observed situation where objective evidence indicates the non-fulfillment of a specified ISM Code requirement.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'internal audit',
    partOfSpeech: '명사',
    meaning: ['선내 자체 감사'],
    englishDefinition: 'A systematic verification carried out by company auditors to verify that onboard operations comply with the safety management system.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'corrective action',
    partOfSpeech: '명사',
    meaning: ['시정 조치'],
    englishDefinition: 'Action taken to eliminate the root cause of a detected non-conformity or defect to prevent recurrence.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'permit to work',
    partOfSpeech: '명사',
    meaning: ['작업 허가서', 'PTW'],
    englishDefinition: 'A formal safety authorization required before undertaking hazardous work onboard like hot work or enclosed entry.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'risk assessment',
    partOfSpeech: '명사',
    meaning: ['위험성 평가'],
    englishDefinition: 'A careful systematic evaluation of potential job hazards and the implementation of protective control measures.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'hot work permit',
    partOfSpeech: '명사',
    meaning: ['화기 작업 허가서'],
    englishDefinition: 'A documented permit approving welding, torch cutting, or grinding in areas where flammable vapors might exist.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'enclosed space entry permit',
    partOfSpeech: '명사',
    meaning: ['밀폐구역 진입 허가서'],
    englishDefinition: 'A verified safety checklist required before any crew enters oxygen-deficient or toxic spaces like ballast tanks.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'lock-out tag-out',
    partOfSpeech: '명사',
    meaning: ['위험설비 차단 및 표식 부착', 'LOTO'],
    englishDefinition: 'A safety procedure locking electrical breakers and hanging tags to prevent accidental equipment energization during maintenance.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'near-miss',
    partOfSpeech: '명사',
    meaning: ['아차사고', '준사고'],
    englishDefinition: 'An unplanned event that did not result in injury or damage, but had the potential to do so if circumstances differed.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'toolbox meeting',
    partOfSpeech: '명사',
    meaning: ['작업 전 안전 미팅', 'TBM'],
    englishDefinition: 'A short informal safety briefing held immediately prior to commencing a hazardous task to review hazards and PPE.',
    difficulty: 'low',
    topic: 'safety',
  },

  // --- 5. 선적, 화물 및 상선 실무 (Cargo Operations & Commercial Shipping) ---
  {
    word: 'bill of lading',
    partOfSpeech: '명사',
    meaning: ['선하증권', 'B/L'],
    englishDefinition: 'A legal maritime document acting as a receipt of cargo, a contract of carriage, and a document of title.',
    difficulty: 'low',
    topic: 'cargo',
  },
  {
    word: "mate's receipt",
    partOfSpeech: '명사',
    meaning: ['본선 수취증', 'M/R'],
    englishDefinition: 'A document signed by the chief officer acknowledging receipt of cargo on board before the formal B/L is issued.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'cargo manifest',
    partOfSpeech: '명사',
    meaning: ['적하목록'],
    englishDefinition: 'A comprehensive customs shipping document giving complete particulars of all cargo items loaded on board.',
    difficulty: 'low',
    topic: 'cargo',
  },
  {
    word: 'stowage factor',
    partOfSpeech: '명사',
    meaning: ['적화계수', '재화계수'],
    englishDefinition: 'The cubic space in cubic meters or feet occupied by one metric ton of a specific commodity in a cargo hold.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'ullage survey',
    partOfSpeech: '명사',
    meaning: ['얼리지 검량', '유면 계측 검사'],
    englishDefinition: 'Measuring liquid cargo volumes in tanker holds by calculating the unfilled space from the top reference point to liquid surface.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'dunnage',
    partOfSpeech: '명사',
    meaning: ['깔판목', '화물 깔개'],
    englishDefinition: 'Loose timber, mats, or inflatables placed between cargo and hold surfaces to protect against moisture and friction.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'lashing',
    partOfSpeech: '명사',
    meaning: ['화물 고박', '고정'],
    englishDefinition: 'Securing cargo using chains, steel wires, or fiber straps to withstand rolling and pitching movements at sea.',
    difficulty: 'low',
    topic: 'cargo',
  },
  {
    word: 'twistlock',
    partOfSpeech: '명사',
    meaning: ['트위스트록', '컨테이너 결속구'],
    englishDefinition: 'A mechanical rotating connector fitted into corner castings to lock stacked shipping containers together.',
    difficulty: 'low',
    topic: 'cargo',
  },
  {
    word: 'turnbuckle',
    partOfSpeech: '명사',
    meaning: ['턴버클', '당김나사'],
    englishDefinition: 'A threaded coupling sleeve used to tension lashing wires and anchor chains firmly.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'cargo sweat',
    partOfSpeech: '명사',
    meaning: ['화물 한', '화물 땀'],
    englishDefinition: 'Moisture condensation occurring directly onto cargo surfaces when warm humid air enters a cold cargo hold.',
    difficulty: 'high',
    topic: 'cargo',
  },
  {
    word: 'ship sweat',
    partOfSpeech: '명사',
    meaning: ['선체 한', '선체 땀'],
    englishDefinition: 'Condensation forming on cold hull steel framing when a vessel loaded with warm cargo sails into colder climates.',
    difficulty: 'high',
    topic: 'cargo',
  },
  {
    word: 'hygrometer',
    partOfSpeech: '명사',
    meaning: ['건습구 습도계'],
    englishDefinition: 'An instrument used to measure relative humidity and determine dew point temperatures in cargo holds.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'dew point',
    partOfSpeech: '명사',
    meaning: ['이슬점', '노점'],
    englishDefinition: 'The atmospheric temperature below which water vapor in the air condenses into liquid droplets.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'laytime',
    partOfSpeech: '명사',
    meaning: ['정박 기간', '하역 허용일수'],
    englishDefinition: 'The agreed period of time allowed to a charterer in a charterparty for loading or discharging cargo without penalty.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'demurrage',
    partOfSpeech: '명사',
    meaning: ['체선료'],
    englishDefinition: 'A liquidated financial penalty paid by the charterer to the shipowner for exceeding agreed laytime.',
    difficulty: 'low',
    topic: 'cargo',
  },
  {
    word: 'despatch money',
    partOfSpeech: '명사',
    meaning: ['조출료'],
    englishDefinition: 'A bonus reward paid by the shipowner to the charterer for completing cargo operations ahead of stipulated laytime.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'notice of readiness',
    partOfSpeech: '명사',
    meaning: ['하역준비완료통지서', 'NOR'],
    englishDefinition: 'Formal written notice served by the master certifying that the ship has arrived and is ready in all respects to load or discharge.',
    difficulty: 'low',
    topic: 'cargo',
  },
  {
    word: 'statement of facts',
    partOfSpeech: '명사',
    meaning: ['사실증명서', 'SOF'],
    englishDefinition: 'A chronological day-by-day record of cargo operations, weather delays, and shift stoppages logged by the port agent.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'deadfreight',
    partOfSpeech: '명사',
    meaning: ['부선료', '공적운임'],
    englishDefinition: 'Compensation payable to the shipowner when a charterer fails to supply the full agreed quantity of cargo.',
    difficulty: 'high',
    topic: 'cargo',
  },
  {
    word: 'general average',
    partOfSpeech: '명사',
    meaning: ['공동해손'],
    englishDefinition: 'A maritime principle where extraordinary sacrifices or expenses voluntarily incurred to preserve common maritime property are shared proportionally by all interests.',
    difficulty: 'high',
    topic: 'safety',
  },
  {
    word: 'particular average',
    partOfSpeech: '명사',
    meaning: ['단독해손'],
    englishDefinition: 'A partial accidental loss or damage suffered by a specific party cargo or hull borne exclusively by the owner or underwriter.',
    difficulty: 'high',
    topic: 'safety',
  },
  {
    word: 'protection and indemnity club',
    partOfSpeech: '명사',
    meaning: ['선주상호보험조합', 'P&I Club'],
    englishDefinition: 'A mutual insurance association providing cover for open liabilities like oil pollution, crew injury, and third-party collision damages.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'classification society',
    partOfSpeech: '명사',
    meaning: ['선급 협회'],
    englishDefinition: 'A non-governmental organization (e.g. KR, DNV, LR) establishing and verifying technical standards for ship construction and seaworthiness.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'condition of class',
    partOfSpeech: '명사',
    meaning: ['선급 지정 조건', '선급 추천사항'],
    englishDefinition: 'A mandatory requirement imposed by class surveyors requiring specified structural or mechanical repairs by a set deadline.',
    difficulty: 'high',
    topic: 'safety',
  },
  {
    word: 'port state control',
    partOfSpeech: '명사',
    meaning: ['항만국 통제', 'PSC'],
    englishDefinition: 'The inspection of foreign ships in national ports to verify compliance with international safety and environmental conventions.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'deficiency',
    partOfSpeech: '명사',
    meaning: ['지적 결함 사항', '결함'],
    englishDefinition: 'A non-fulfillment of international convention standards noted during a Port State Control (PSC) inspection.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'detention',
    partOfSpeech: '명사',
    meaning: ['출항 정지', '디텐션'],
    englishDefinition: 'The formal prohibition of a ship from going to sea due to serious safety hazards until rectified.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'vetting inspection',
    partOfSpeech: '명사',
    meaning: ['화주 안전성 검사', '베팅 인스펙션'],
    englishDefinition: 'An exhaustive safety audit conducted by major oil or chartering corporations (e.g. SIRE) prior to chartering.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'ship-to-ship transfer',
    partOfSpeech: '명사',
    meaning: ['선박 간 해상 환적', 'STS'],
    englishDefinition: 'The transfer of crude or chemical cargo between two vessels moored alongside each other at sea or at anchorage.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'monkey island',
    partOfSpeech: '명사',
    meaning: ['몽키 아일랜드', '콤파스 갑판'],
    englishDefinition: 'The highest accessible open deck area situated immediately above the navigation bridge wheelhouse.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'bridge navigational watch alarm system',
    partOfSpeech: '명사',
    meaning: ['선교 당직 무반응 경보장치', 'BNWAS'],
    englishDefinition: 'An electronic timer monitoring officer alertness on the bridge that sounds backup cabin alarms if no movement occurs within preset intervals.',
    difficulty: 'medium',
    topic: 'safety',
  },
];

export function buildMaritimePhase3Database() {
  const pPath = path.resolve('public/data/maritime_smcp_v1.json');
  if (!fs.existsSync(pPath)) {
    throw new Error(`파일이 존재하지 않습니다: ${pPath}`);
  }
  const currentData = JSON.parse(fs.readFileSync(pPath, 'utf-8'));
  const currentWords: MaritimeWordEntry[] = currentData.words;
  console.log(`[현재 DB] 기존 어휘 수: ${currentWords.length}`);

  // 중복 검사
  const existingSet = new Set<string>(currentWords.map((w) => w.word.toLowerCase().trim()));
  const p3Set = new Set<string>();

  for (const item of conventionsAndPracticeWords) {
    const lower = item.word.toLowerCase().trim();
    if (existingSet.has(lower)) {
      throw new Error(`[중복 발견] 기존 DB에 이미 존재하는 어휘입니다: ${item.word}`);
    }
    if (p3Set.has(lower)) {
      throw new Error(`[중복 발견] Phase 3 내에서 중복된 어휘입니다: ${item.word}`);
    }
    p3Set.add(lower);
  }
  console.log(`[Phase 3] 신규 국제협약 및 실무 어휘 수: ${conventionsAndPracticeWords.length} (중복 0건)`);

  const combinedList: MaritimeWordEntry[] = [
    ...currentWords,
    ...conventionsAndPracticeWords.map((item, idx) => ({
      id: currentWords.length + idx + 1,
      ...item,
    })),
  ];

  const database = {
    databaseVersion: 3,
    name: 'IMO SMCP & 해기사 3·4급 & 국제협약 해사영어',
    category: 'maritime_full_master',
    phase: 'PHASE_3_CONVENTIONS_AND_PRACTICE_EXPANSION',
    description: 'IMO SMCP 174어 + 해기사 3·4급 빈출 171어 + 국제해사협약(COLREGs/SOLAS/MARPOL/STCW/ISM) 및 선박실무 106어 누적 총 451어 완전 구축',
    wordCount: combinedList.length,
    words: combinedList,
  };
  fs.writeFileSync(pPath, JSON.stringify(database, null, 2), 'utf-8');
  console.log(`[Success] ${pPath} 파일 갱신 완료! 총 어휘 수: ${combinedList.length}개`);
}

if (process.argv[1] && process.argv[1].includes('generateMaritimePhase3.ts')) {
  buildMaritimePhase3Database();
}
