import fs from 'fs';
import path from 'path';

export interface MaritimeWordEntry {
  id: number;
  word: string;
  partOfSpeech: string;
  meaning: string[];
  englishDefinition: string;
  difficulty: 'low' | 'medium' | 'high';
  topic: 'navigation' | 'emergency' | 'safety' | 'cargo' | 'communication' | 'engine';
}

// 해기사 3급·4급(항해사/기관사) 국가자격시험 해사영어 빈출 180어 (해경 제외)
export const officerExamWords: Array<Omit<MaritimeWordEntry, 'id'>> = [
  // --- 1. 항해 및 천문/지문 항법 (Navigation & Celestial/Terrestrial) ---
  {
    word: 'azimuth',
    partOfSpeech: '명사',
    meaning: ['방위각', '천체 방위각'],
    englishDefinition: 'The horizontal angle or direction of a celestial object measured clockwise from the north.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'zenith',
    partOfSpeech: '명사',
    meaning: ['천정', '정점'],
    englishDefinition: 'The point on the celestial sphere directly above an observer on the ship.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'dead reckoning',
    partOfSpeech: '명사',
    meaning: ['추측 항법', '추측 선위'],
    englishDefinition: 'The process of calculating current position by using a previously determined position and advancing it based upon estimated speed and course.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'bearing',
    partOfSpeech: '명사',
    meaning: ['방위', '방위선'],
    englishDefinition: 'The horizontal direction of one terrestrial or celestial point from another, expressed as an angular distance.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'variation',
    partOfSpeech: '명사',
    meaning: ['자기 편차', '편차'],
    englishDefinition: 'The horizontal angle between the true meridian and the magnetic meridian at any place.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'deviation',
    partOfSpeech: '명사',
    meaning: ['자차', '나침의 자차'],
    englishDefinition: 'The deflection of the needle of a magnetic compass due to the magnetic properties of the ship itself.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'gyrocompass',
    partOfSpeech: '명사',
    meaning: ['전륜나침의', '자이로컴퍼스'],
    englishDefinition: 'A compass that finds true north by using an electrically driven gyroscope unaffected by magnetic fields.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'magnetic compass',
    partOfSpeech: '명사',
    meaning: ['자기나침의', '마그네틱 컴퍼스'],
    englishDefinition: 'A navigation instrument that indicates direction relative to the earth magnetic poles.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'chart datum',
    partOfSpeech: '명사',
    meaning: ['해도 기준면', '수로 기준면'],
    englishDefinition: 'The level of water to which soundings and drying heights on a nautical chart are referred.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'great circle',
    partOfSpeech: '명사',
    meaning: ['대권', '대권항로'],
    englishDefinition: 'A circle on the surface of a sphere whose center and radius are those of the sphere, providing the shortest distance.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'rhumb line',
    partOfSpeech: '명사',
    meaning: ['점장항로', '등각항로'],
    englishDefinition: 'A line on the earth surface that crosses all meridians of longitude at the same angle.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'position fix',
    partOfSpeech: '명사',
    meaning: ['실측 선위', '선위 결정'],
    englishDefinition: 'A reliable position determined by observing two or more intersecting lines of position.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'range light',
    partOfSpeech: '명사',
    meaning: ['도등', '선위유도등'],
    englishDefinition: 'Two or more aligned navigation lights indicating the centerline of a safe navigable channel.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'light beacon',
    partOfSpeech: '명사',
    meaning: ['등표', '항로 표지'],
    englishDefinition: 'An unstaffed fixed navigation mark fitted with a light to warn vessels of hazards.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'lighthouse',
    partOfSpeech: '명사',
    meaning: ['등대'],
    englishDefinition: 'A coastal tower with a powerful beam serving as a principal navigational aid for ships.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'tidal stream',
    partOfSpeech: '명사',
    meaning: ['조류', '해조'],
    englishDefinition: 'The alternating horizontal movement of water associated with the rise and fall of the tide.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'spring tide',
    partOfSpeech: '명사',
    meaning: ['대조', '사리'],
    englishDefinition: 'A tide that occurs around the time of new or full moon when the tidal range is greatest.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'neap tide',
    partOfSpeech: '명사',
    meaning: ['소조', '조금'],
    englishDefinition: 'A tide that occurs around the first and third quarters of the moon when the tidal range is lowest.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'flood tide',
    partOfSpeech: '명사',
    meaning: ['창조', '밀물'],
    englishDefinition: 'The incoming tidal flow between low water and the following high water.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'ebb tide',
    partOfSpeech: '명사',
    meaning: ['낙조', '썰물'],
    englishDefinition: 'The period between high tide and the succeeding low tide in which the water recedes.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'slack water',
    partOfSpeech: '명사',
    meaning: ['정조', '게류'],
    englishDefinition: 'A short period in a body of tidal water when the water is completely unstressed, and there is no movement either way.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'nautical chart',
    partOfSpeech: '명사',
    meaning: ['해도', '항해용 해도'],
    englishDefinition: 'A specialized map depicting water depths, coastal features, navigational hazards, and aids to navigation.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'sextant',
    partOfSpeech: '명사',
    meaning: ['육분의', '천체 고도 측정기'],
    englishDefinition: 'An optical instrument used to measure the angle between an astronomical object and the horizon for celestial navigation.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'chronometer',
    partOfSpeech: '명사',
    meaning: ['마린 크로노미터', '정밀 항해시계'],
    englishDefinition: 'A highly accurate clock onboard ship used in determining longitude at sea.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'parallel indexing',
    partOfSpeech: '명사',
    meaning: ['평행 색인법', '평행선 레이더 항법'],
    englishDefinition: 'A radar technique to monitor a ship lateral deviation from a planned track along coastlines.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'ARPA',
    partOfSpeech: '명사',
    meaning: ['자동레이더플로팅장치', '아르파'],
    englishDefinition: 'Automatic Radar Plotting Aid that tracks other targets and computes collision risk parameters (CPA/TCPA).',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'AIS',
    partOfSpeech: '명사',
    meaning: ['선박자동식별장치'],
    englishDefinition: 'Automatic Identification System broadcasting ship identity, position, course, and speed to nearby vessels.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'ECDIS',
    partOfSpeech: '명사',
    meaning: ['전자해도표시장치'],
    englishDefinition: 'Electronic Chart Display and Information System complying with IMO navigation standards.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'sea clutter',
    partOfSpeech: '명사',
    meaning: ['해면 반사파', '해면 잡음'],
    englishDefinition: 'Radar echoes caused by reflections from surrounding sea waves that mask smaller targets.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'rain clutter',
    partOfSpeech: '명사',
    meaning: ['우설 반사파', '강우 잡음'],
    englishDefinition: 'Unwanted radar reflections returned from heavy rain, snow, or atmospheric precipitation.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'range ring',
    partOfSpeech: '명사',
    meaning: ['거리 환', '레이더 등거리원'],
    englishDefinition: 'Concentric circular rings on a radar display used for estimating target distances.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'electronic bearing line',
    partOfSpeech: '명사',
    meaning: ['전자방위선', 'EBL'],
    englishDefinition: 'A controllable bearing cursor on a radar display used to measure the bearing of any target.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'variable range marker',
    partOfSpeech: '명사',
    meaning: ['가변거리표', 'VRM'],
    englishDefinition: 'An adjustable circular ring on a radar screen used to measure the precise range to a target.',
    difficulty: 'medium',
    topic: 'navigation',
  },

  // --- 2. 선체 조종 및 선박 역학 (Ship Maneuvering & Dynamics) ---
  {
    word: 'squat',
    partOfSpeech: '명사',
    meaning: ['선체 침하', '침하 현상'],
    englishDefinition: 'The hydrodynamic bodily sinkage and trim change of a vessel proceeding through shallow water.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'bank effect',
    partOfSpeech: '명사',
    meaning: ['제방 효과', '수로 제방 반발력'],
    englishDefinition: 'The hydrodynamic suction and cushioning effect pushing bow away and drawing stern toward a canal bank.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'shallow water effect',
    partOfSpeech: '명사',
    meaning: ['천수 영향', '천수 효과'],
    englishDefinition: 'Changes in a ship maneuvering characteristics, speed reduction, and vibration when navigating in shallow depth.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'interaction',
    partOfSpeech: '명사',
    meaning: ['선박 간 상호작용', '간섭 현상'],
    englishDefinition: 'Mutual hydrodynamic forces exerted between two vessels passing or overtaking close to each other.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'turning circle',
    partOfSpeech: '명사',
    meaning: ['선회권', '선회 궤적'],
    englishDefinition: 'The path described by the center of gravity of a vessel when executing a full 360-degree turn under rudder.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'pivot point',
    partOfSpeech: '명사',
    meaning: ['선회 중심점', '피벗 포인트'],
    englishDefinition: 'The point on a vessel centerline about which the ship turns during a course alteration.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'advance',
    partOfSpeech: '명사',
    meaning: ['종거', '선회 전진 거리'],
    englishDefinition: 'The distance traveled by a ship original heading from the initial rudder order to completion of 90 degrees turn.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'transfer',
    partOfSpeech: '명사',
    meaning: ['횡거', '선회 횡이동 거리'],
    englishDefinition: 'The lateral distance moved by a ship from its original line of advance during a 90-degree alteration of course.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'tactical diameter',
    partOfSpeech: '명사',
    meaning: ['전술 선회경', '전술 직경'],
    englishDefinition: 'The lateral distance from original heading to the point where the vessel has completed 180 degrees of turn.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'stopping distance',
    partOfSpeech: '명사',
    meaning: ['정지 거리', '제동 거리'],
    englishDefinition: 'The total distance a vessel travels through the water from full ahead until completely brought to a standstill.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'head reach',
    partOfSpeech: '명사',
    meaning: ['정지 타력 거리', '전진 타력'],
    englishDefinition: 'The distance a vessel continues to advance along its original course during a crash-stop maneuver.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'sternway',
    partOfSpeech: '명사',
    meaning: ['후진 타력', '후진력'],
    englishDefinition: 'The backward motion or stern-first movement of a ship through the water.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'yawing',
    partOfSpeech: '명사',
    meaning: ['선수 요동', '요잉'],
    englishDefinition: 'The rotation of a vessel about its vertical axis, causing its heading to swing from side to side.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'pitching',
    partOfSpeech: '명사',
    meaning: ['종동', '피칭'],
    englishDefinition: 'The periodic up-and-down rotational motion of a vessel bow and stern about its transverse axis.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'rolling',
    partOfSpeech: '명사',
    meaning: ['횡동', '롤링'],
    englishDefinition: 'The side-to-side tilting or rotational movement of a vessel from port to starboard about its longitudinal axis.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'heaving',
    partOfSpeech: '명사',
    meaning: ['상하동', '히빙'],
    englishDefinition: 'The bodily linear up-and-down motion of the entire ship in sea waves.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'surging',
    partOfSpeech: '명사',
    meaning: ['전후동', '서징'],
    englishDefinition: 'The linear fore-and-aft bodily translation motion of a vessel along its longitudinal axis.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'swaying',
    partOfSpeech: '명사',
    meaning: ['좌우동', '스웨잉'],
    englishDefinition: 'The lateral bodily translation motion of a vessel from side to side without turning.',
    difficulty: 'medium',
    topic: 'navigation',
  },

  // --- 3. 묘박 및 계선 설비 (Mooring, Anchoring & Deck Machinery) ---
  {
    word: 'hawse pipe',
    partOfSpeech: '명사',
    meaning: ['묘쇄관', '닻줄 구멍'],
    englishDefinition: 'A pipe through a vessel bow plating through which the anchor cable runs.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'chain locker',
    partOfSpeech: '명사',
    meaning: ['묘쇄고', '닻줄 보관고'],
    englishDefinition: 'A dedicated compartment below deck forward used for stowing the anchor chain cable.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'dragging anchor',
    partOfSpeech: '명사',
    meaning: ['주묘', '닻 끌림'],
    englishDefinition: 'The dangerous unintentional sliding of an anchor along the seabed due to strong current or wind.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'foul anchor',
    partOfSpeech: '명사',
    meaning: ['얽힌 닻', '파울 앵커'],
    englishDefinition: 'An anchor whose fluke or shank has become entangled with its own cable or an underwater obstacle.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'anchor flukes',
    partOfSpeech: '명사',
    meaning: ['닻가지', '닻발'],
    englishDefinition: 'The pointed triangular palms of an anchor that dig into the sea bottom.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'anchor crown',
    partOfSpeech: '명사',
    meaning: ['닻머리', '닻 크라운'],
    englishDefinition: 'The lower bottom junction where the shank joins the anchor arms.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'spring line',
    partOfSpeech: '명사',
    meaning: ['스프링 라인', '억제줄'],
    englishDefinition: 'A mooring line led forward or aft from the ship to prevent fore-and-aft movement along the berth.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'breast line',
    partOfSpeech: '명사',
    meaning: ['브레스트 라인', '직박줄'],
    englishDefinition: 'A mooring rope led at right angles to the ship side to keep the vessel close against the quay.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'head line',
    partOfSpeech: '명사',
    meaning: ['헤드 라인', '선수 계선줄'],
    englishDefinition: 'A mooring line running forward from the bow to hold the ship bow in position.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'stern line',
    partOfSpeech: '명사',
    meaning: ['스턴 라인', '선미 계선줄'],
    englishDefinition: 'A mooring line running aft from the stern to secure the vessel stern to the jetty.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'heaving line',
    partOfSpeech: '명사',
    meaning: ['투삭줄', '연락줄'],
    englishDefinition: 'A light weighted rope thrown to shore or another vessel to pass heavy mooring hawsers.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'messenger line',
    partOfSpeech: '명사',
    meaning: ['중간 예인줄', '메신저 와이어'],
    englishDefinition: 'An intermediate line used to haul a heavier cable across between two vessels or ship to shore.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'bitter end',
    partOfSpeech: '명사',
    meaning: ['닻줄 고정단', '비터 엔드'],
    englishDefinition: 'The inboard extreme end of the anchor cable secured to the chain locker bulkhead.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: "devil's claw",
    partOfSpeech: '명사',
    meaning: ['체인 압착 제동기', '데빌스 클로'],
    englishDefinition: 'A steel turnbuckle device fitted with two claws used to secure the anchor cable firmly at sea.',
    difficulty: 'high',
    topic: 'navigation',
  },

  // --- 4. 선체 구조 및 복원성 (Hull Structure, Stability & Trim) ---
  {
    word: 'keel',
    partOfSpeech: '명사',
    meaning: ['용골', '선체 바닥 중심재'],
    englishDefinition: 'The central longitudinal structural member running along the lowest centerline of a ship bottom.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'frame',
    partOfSpeech: '명사',
    meaning: ['늑골', '선체 뼈대'],
    englishDefinition: 'Transverse structural rib supporting the side and bottom shell plating of the hull.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'transverse bulkhead',
    partOfSpeech: '명사',
    meaning: ['횡격벽'],
    englishDefinition: 'An athwartship vertical partition dividing the hull into watertight compartments.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'longitudinal bulkhead',
    partOfSpeech: '명사',
    meaning: ['종격벽'],
    englishDefinition: 'A fore-and-aft vertical partition running lengthwise through the ship to provide structural strength.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'double bottom',
    partOfSpeech: '명사',
    meaning: ['이중저'],
    englishDefinition: 'The watertight space between the outer bottom shell and the inner bottom plating of a ship.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'cofferdam',
    partOfSpeech: '명사',
    meaning: ['코퍼댐', '격리실'],
    englishDefinition: 'An empty protective void space between two bulkheads separating incompatible compartments (e.g. fuel and freshwater).',
    difficulty: 'high',
    topic: 'safety',
  },
  {
    word: 'collision bulkhead',
    partOfSpeech: '명사',
    meaning: ['선수 충돌격벽'],
    englishDefinition: 'The foremost major watertight bulkhead designed to retain watertight integrity following bow impact.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'forecastle',
    partOfSpeech: '명사',
    meaning: ['선수루', '포캐슬'],
    englishDefinition: 'The raised superstructure or weather deck section situated at the extreme forward end of the ship.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'poop deck',
    partOfSpeech: '명사',
    meaning: ['선미루갑판', '풉 데크'],
    englishDefinition: 'A raised deck above the weather deck located at the extreme stern of a ship.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'displacement',
    partOfSpeech: '명사',
    meaning: ['배수량', '배수 톤수'],
    englishDefinition: 'The actual total weight of a ship and all its contents, equivalent to the mass of water it displaces.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'deadweight',
    partOfSpeech: '명사',
    meaning: ['재화중량톤수', 'DWT'],
    englishDefinition: 'The total carrying capacity of a ship including cargo, fuel, ballast, fresh water, stores, and crew.',
    difficulty: 'low',
    topic: 'cargo',
  },
  {
    word: 'light ship weight',
    partOfSpeech: '명사',
    meaning: ['경하중량', '경하 선박 중량'],
    englishDefinition: 'The weight of the ship completely empty without cargo, fuel, ballast, water, or passengers.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'center of gravity',
    partOfSpeech: '명사',
    meaning: ['무게 중심', '중심 (G)'],
    englishDefinition: 'The single point at which the entire combined downward gravitational weight of a ship is considered to act.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'center of buoyancy',
    partOfSpeech: '명사',
    meaning: ['부심', '부력 중심 (B)'],
    englishDefinition: 'The geometric center of the underwater submerged volume of a vessel where total upward buoyancy acts.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'metacenter',
    partOfSpeech: '명사',
    meaning: ['경심', '메타센터 (M)'],
    englishDefinition: 'The intersection point of the vertical line through the center of buoyancy with the initial center line when tilted.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'metacentric height',
    partOfSpeech: '명사',
    meaning: ['경심고', 'GM'],
    englishDefinition: 'The vertical distance between the center of gravity (G) and the metacenter (M), representing initial stability.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'righting lever',
    partOfSpeech: '명사',
    meaning: ['복원 정', '복원 레버 (GZ)'],
    englishDefinition: 'The perpendicular distance between the vertical line of buoyant force and the center of gravity, generating righting moment.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'stiff ship',
    partOfSpeech: '명사',
    meaning: ['강선', '경심고가 과대하여 급격히 복원되는 선박'],
    englishDefinition: 'A ship with an excessively large GM that rolls very quickly and violently, causing severe structural stresses.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'tender ship',
    partOfSpeech: '명사',
    meaning: ['유선', '경심고가 작아 롤링 주기가 긴 선박'],
    englishDefinition: 'A ship with a small GM having a sluggish rolling motion and lingering dangerously at large heel angles.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'hogging',
    partOfSpeech: '명사',
    meaning: ['호깅', '선체 중앙부가 위로 솟는 굽힘 현상'],
    englishDefinition: 'A hull longitudinal bending condition where the midships area is pushed upward while ends drop down.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'sagging',
    partOfSpeech: '명사',
    meaning: ['새깅', '선체 중앙부가 아래로 처지는 굽힘 현상'],
    englishDefinition: 'A longitudinal bending condition where the midship section is deflected downward below bow and stern.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'free surface effect',
    partOfSpeech: '명사',
    meaning: ['자유표면효과'],
    englishDefinition: 'The virtual loss of metacentric height (GM) caused by the sloshing of liquid in slack or partially filled tanks.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'draft marks',
    partOfSpeech: '명사',
    meaning: ['흘수 표척', '흘수 눈금'],
    englishDefinition: 'Numbers marked at the bow, midships, and stern indicating the vertical distance to the bottom of the keel.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'Plimsoll mark',
    partOfSpeech: '명사',
    meaning: ['만재흘수선 표식', '플림솔 마크'],
    englishDefinition: 'The official reference mark painted amidships on both sides of a hull indicating the maximum legal submersion limit.',
    difficulty: 'medium',
    topic: 'safety',
  },

  // --- 5. 디젤 주기관 (Marine Diesel Main Propulsion Engine) ---
  {
    word: 'cylinder liner',
    partOfSpeech: '명사',
    meaning: ['실린더 라이너'],
    englishDefinition: 'A replaceable cylindrical sleeve inside the engine block inside which the piston reciprocates.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'cylinder head',
    partOfSpeech: '명사',
    meaning: ['실린더 헤드', '실린더 커버'],
    englishDefinition: 'The heavy top enclosure sealing the upper end of the combustion cylinder containing valves and injector.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'piston crown',
    partOfSpeech: '명사',
    meaning: ['피스톤 크라운', '피스톤 두부'],
    englishDefinition: 'The heat-resistant upper top surface of a piston exposed directly to high combustion temperatures and pressures.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'piston skirt',
    partOfSpeech: '명사',
    meaning: ['피스톤 스커트'],
    englishDefinition: 'The cylindrical bottom section of a piston that guides it along the cylinder liner bore.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'piston ring',
    partOfSpeech: '명사',
    meaning: ['피스톤 링'],
    englishDefinition: 'Split metallic rings fitted into piston grooves to seal combustion pressure and wipe lubricating oil.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'connecting rod',
    partOfSpeech: '명사',
    meaning: ['연접봉', '커넥팅 로드'],
    englishDefinition: 'A mechanical link that connects the crosshead or piston pin to the crankshaft to convert reciprocating motion into rotation.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'crankshaft',
    partOfSpeech: '명사',
    meaning: ['크랭크축'],
    englishDefinition: 'The main heavy shaft driven by pistons to deliver engine rotational propulsion torque to the propeller.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'camshaft',
    partOfSpeech: '명사',
    meaning: ['캠축'],
    englishDefinition: 'A rotating shaft equipped with profiled cams used to actuate intake, exhaust valves and fuel injection pumps.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'flywheel',
    partOfSpeech: '명사',
    meaning: ['플라이휠'],
    englishDefinition: 'A massive heavy wheel attached to the crankshaft that smoothes out cyclical torque fluctuations.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'crosshead',
    partOfSpeech: '명사',
    meaning: ['크로스헤드'],
    englishDefinition: 'A sliding joint in large low-speed marine diesel engines that absorbs side thrust and guides the piston rod.',
    difficulty: 'high',
    topic: 'engine',
  },
  {
    word: 'stuffing box',
    partOfSpeech: '명사',
    meaning: ['스터핑 박스', '격벽 기밀장치'],
    englishDefinition: 'A sealing assembly around the piston rod preventing scavenge air and dirty cylinder oil from entering the crankcase.',
    difficulty: 'high',
    topic: 'engine',
  },
  {
    word: 'bedplate',
    partOfSpeech: '명사',
    meaning: ['베드플레이트', '엔진 대판'],
    englishDefinition: 'The rigid foundation structure at the base of a marine diesel engine supporting the main bearings and crankshaft.',
    difficulty: 'high',
    topic: 'engine',
  },
  {
    word: 'thrust bearing',
    partOfSpeech: '명사',
    meaning: ['추력 베어링', '스러스트 베어링'],
    englishDefinition: 'The primary heavy bearing that absorbs axial propeller thrust forces and transfers them directly to the ship hull.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'propeller shaft',
    partOfSpeech: '명사',
    meaning: ['추진축', '프로펠러 축'],
    englishDefinition: 'The steel shaft transmitting rotational power from the main engine through the stern tube to the propeller.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'stern tube',
    partOfSpeech: '명사',
    meaning: ['선미관'],
    englishDefinition: 'The watertight shaft casing through which the propeller shaft penetrates the aft hull structure.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'controllable pitch propeller',
    partOfSpeech: '명사',
    meaning: ['가변피치 프로펠러', 'CPP'],
    englishDefinition: 'A propeller whose blade angle can be adjusted during operation to change ship speed and reverse direction without altering engine rotation.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'fixed pitch propeller',
    partOfSpeech: '명사',
    meaning: ['고정피치 프로펠러', 'FPP'],
    englishDefinition: 'A propeller whose blades are permanently cast into a rigid fixed orientation.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'turbocharger',
    partOfSpeech: '명사',
    meaning: ['배기가스 터보과급기'],
    englishDefinition: 'An exhaust-gas-driven turbine driving a compressor that forces dense pressurized combustion air into engine cylinders.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'scavenge air',
    partOfSpeech: '명사',
    meaning: ['소기', '스캐빈징 공기'],
    englishDefinition: 'Pressurized fresh air admitted into a 2-stroke diesel cylinder to expel residual burnt exhaust gases and charge fresh oxygen.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'exhaust manifold',
    partOfSpeech: '명사',
    meaning: ['배기 다기관'],
    englishDefinition: 'The insulated pipe assembly that gathers hot exhaust gas from multiple cylinders and directs it into the turbocharger.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'fuel injection valve',
    partOfSpeech: '명사',
    meaning: ['연료분사밸브', '인젝터'],
    englishDefinition: 'An atomizing nozzle that injects fine high-pressure fuel spray into the combustion chamber.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'fuel injection pump',
    partOfSpeech: '명사',
    meaning: ['연료분사펌프'],
    englishDefinition: 'A reciprocating pump that meters and pressurizes fuel oil to several hundred bars for timed injection.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'crankcase explosion',
    partOfSpeech: '명사',
    meaning: ['크랭크케이스 폭발'],
    englishDefinition: 'A violent combustion accident caused when hot bearing spots ignite accumulated oil mist inside an engine crankcase.',
    difficulty: 'high',
    topic: 'emergency',
  },
  {
    word: 'relief valve',
    partOfSpeech: '명사',
    meaning: ['릴리프 밸브', '압력 방출 밸브'],
    englishDefinition: 'An automatic spring-loaded valve that discharges fluid to prevent dangerous overpressure in cylinders or pipes.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'scavenging trunk',
    partOfSpeech: '명사',
    meaning: ['소기실', '스캐빈징 트렁크'],
    englishDefinition: 'The receiver plenum compartment containing pressurized scavenging air surrounding the cylinder liner ports.',
    difficulty: 'high',
    topic: 'engine',
  },
  {
    word: 'air cooler',
    partOfSpeech: '명사',
    meaning: ['공기 냉각기', '인터쿨러'],
    englishDefinition: 'A heat exchanger that cools compressed scavenge air to increase its density before entering the cylinders.',
    difficulty: 'medium',
    topic: 'engine',
  },

  // --- 6. 보조 기계 및 보일러 (Auxiliary Machinery, Boilers & Purifiers) ---
  {
    word: 'auxiliary boiler',
    partOfSpeech: '명사',
    meaning: ['보조 보일러'],
    englishDefinition: 'A steam generator fired onboard to heat bunker tanks, accommodation, and cargo heaters while in port or underway.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'economizer',
    partOfSpeech: '명사',
    meaning: ['절탄기', '배기가스 보일러'],
    englishDefinition: 'A heat exchanger utilizing waste heat from main engine exhaust gas to generate steam while at sea.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'safety valve',
    partOfSpeech: '명사',
    meaning: ['안전 밸브'],
    englishDefinition: 'An autonomous spring-loaded pressure relief device fitted to a boiler steam drum to prevent catastrophic bursting.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'gauge glass',
    partOfSpeech: '명사',
    meaning: ['수면계 유리', '보일러 수면계'],
    englishDefinition: 'A thick transparent visual sight tube on a boiler displaying the current operating water level.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'burner',
    partOfSpeech: '명사',
    meaning: ['보일러 버너', '연소 버너'],
    englishDefinition: 'The firing nozzle mechanism atomizing and igniting fuel inside a boiler furnace.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'feed water pump',
    partOfSpeech: '명사',
    meaning: ['급수 펌프'],
    englishDefinition: 'A high-pressure pump that forces treated water into a boiler against its internal steam pressure.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'condenser',
    partOfSpeech: '명사',
    meaning: ['복수기', '응축기'],
    englishDefinition: 'A heat exchanger that cools spent exhaust steam back into water for boiler feed recycling.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'centrifugal purifier',
    partOfSpeech: '명사',
    meaning: ['원심식 청정기', '퓨리파이어'],
    englishDefinition: 'A high-speed centrifugal centrifuge used to remove water and solid impurities from heavy fuel and lube oils.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'clarifier',
    partOfSpeech: '명사',
    meaning: ['원심식 정유기', '클라리파이어'],
    englishDefinition: 'A centrifuge configured specifically to separate finely suspended solid particles from fuel oil without water seal.',
    difficulty: 'high',
    topic: 'engine',
  },
  {
    word: 'oily water separator',
    partOfSpeech: '명사',
    meaning: ['유수분리기', 'OWS'],
    englishDefinition: 'An equipment that decontaminates engine room bilge water to less than 15 ppm oil content prior to overboard discharge.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: '15 ppm alarm',
    partOfSpeech: '명사',
    meaning: ['15ppm 유분 경보기', '유분 감시기'],
    englishDefinition: 'An electronic optical monitoring device that halts oily bilge discharge automatically if oil concentration exceeds 15 ppm.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'incinerator',
    partOfSpeech: '명사',
    meaning: ['선내 소각기'],
    englishDefinition: 'A specialized shipboard furnace used to burn waste oil sludges and solid garbage under strict MARPOL standards.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'freshwater generator',
    partOfSpeech: '명사',
    meaning: ['조수기', '해수 담수화 장치'],
    englishDefinition: 'An evaporator using waste jacket cooling water heat to distill seawater into fresh drinking water under vacuum.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'air compressor',
    partOfSpeech: '명사',
    meaning: ['공기 압축기'],
    englishDefinition: 'A high-pressure multi-stage pump that charges compressed air up to 30 bar for starting diesel engines.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'starting air receiver',
    partOfSpeech: '명사',
    meaning: ['기동 공기 저장용기', '에어 보틀'],
    englishDefinition: 'A certified high-pressure steel vessel storing compressed air used for cranking marine engines.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'expansion valve',
    partOfSpeech: '명사',
    meaning: ['팽창 밸브'],
    englishDefinition: 'A refrigeration throttling valve that meters liquid refrigerant pressure drop into the evaporator coil.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'refrigeration compressor',
    partOfSpeech: '명사',
    meaning: ['냉동기 압축기'],
    englishDefinition: 'A mechanical compressor circulating refrigerant vapor throughout the ship provision cold stores or reefer holds.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'evaporator coil',
    partOfSpeech: '명사',
    meaning: ['증발기 코일'],
    englishDefinition: 'The cold heat-exchange tubing wherein expanding refrigerant boils and absorbs ambient heat from refrigerated spaces.',
    difficulty: 'medium',
    topic: 'engine',
  },

  // --- 7. 배관, 탱크, 밸러스트 및 벙커링 (Piping, Tanks, Ballast & Bunkering) ---
  {
    word: 'bunker manifold',
    partOfSpeech: '명사',
    meaning: ['벙커 매니폴드', '연료 수급관 연결구'],
    englishDefinition: 'The main pipe connections on deck amidships where shore bunker hoses are connected for refueling.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'sounding pipe',
    partOfSpeech: '명사',
    meaning: ['측심관'],
    englishDefinition: 'A vertical steel sounding tube extending into a tank bottom through which a weighted sounding tape is lowered.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'ullage pipe',
    partOfSpeech: '명사',
    meaning: ['유면 계측관', '얼리지 파이프'],
    englishDefinition: 'An access opening on top of a cargo oil tank used to measure the depth of the empty vapor space above liquid.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'air vent pipe',
    partOfSpeech: '명사',
    meaning: ['공기 배출관', '통기관'],
    englishDefinition: 'A pipe fitted with flame screen letting air escape from or enter a tank during filling or emptying operations.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'settling tank',
    partOfSpeech: '명사',
    meaning: ['침전 탱크'],
    englishDefinition: 'A heated deep fuel tank wherein water and heavy sediment settle by gravity prior to centrifugal purification.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'service tank',
    partOfSpeech: '명사',
    meaning: ['상용 서비스 탱크', '청정유 일일탱크'],
    englishDefinition: 'A purified fuel oil tank supplying clean oil directly to main and auxiliary engine fuel injection systems.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'double bottom tank',
    partOfSpeech: '명사',
    meaning: ['이중저 탱크'],
    englishDefinition: 'Compartments in the lower hull used alternatively for sea water ballast or fuel oil storage.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'ballast pump',
    partOfSpeech: '명사',
    meaning: ['밸러스트 펌프'],
    englishDefinition: 'A high-capacity centrifugal pump used to fill or discharge seawater from ballast tanks to adjust stability and draft.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'stripping pump',
    partOfSpeech: '명사',
    meaning: ['잔유 배출용 스트리핑 펌프'],
    englishDefinition: 'A positive displacement pump used to suck out the final remaining liquid residues from tank bottoms.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'sea chest',
    partOfSpeech: '명사',
    meaning: ['해수 흡입구', '씨 체스트'],
    englishDefinition: 'A recessed compartment in the hull bottom fitted with strainer gratings through which cooling seawater is drawn.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'sea suction valve',
    partOfSpeech: '명사',
    meaning: ['해수 흡입 밸브'],
    englishDefinition: 'A large valve attached to the sea chest controlling seawater supply to engine cooling and fire pumps.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'overboard discharge valve',
    partOfSpeech: '명사',
    meaning: ['선외 배출 밸브'],
    englishDefinition: 'A hull valve through which circulated cooling water or treated effluent is discharged back into the sea.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'bilge well',
    partOfSpeech: '명사',
    meaning: ['빌지 웰', '오수 집수정'],
    englishDefinition: 'A drainage sump located at the lowest forward and aft corners of an engine room or cargo hold.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'oily bilge tank',
    partOfSpeech: '명사',
    meaning: ['유성 빌지 탱크'],
    englishDefinition: 'A holding tank used to store accumulated oily leakages from machinery before processing through the OWS.',
    difficulty: 'low',
    topic: 'safety',
  },

  // --- 8. 선박 전기 및 자동화 제어 (Electrical & Automation Systems) ---
  {
    word: 'main switchboard',
    partOfSpeech: '명사',
    meaning: ['주 배전반', 'MSB'],
    englishDefinition: 'The primary distribution panel receiving electric power from diesel generators and distributing it throughout the ship.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'emergency switchboard',
    partOfSpeech: '명사',
    meaning: ['비상 배전반', 'ESB'],
    englishDefinition: 'An isolated electrical switchboard energized automatically by the emergency generator during total blackout.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'emergency generator',
    partOfSpeech: '명사',
    meaning: ['비상 발전기'],
    englishDefinition: 'An independent self-contained diesel generator located above the uppermost continuous deck for emergency power.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'circuit breaker',
    partOfSpeech: '명사',
    meaning: ['차단기'],
    englishDefinition: 'An automatic electromagnetic switch designed to interrupt electrical circuits in case of overload or short circuit.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'preferential trip',
    partOfSpeech: '명사',
    meaning: ['우선 차단 장치'],
    englishDefinition: 'A safety relay that automatically disconnects non-essential electrical loads during generator overload to preserve power to navigation and steering.',
    difficulty: 'high',
    topic: 'engine',
  },
  {
    word: 'blackout',
    partOfSpeech: '명사',
    meaning: ['선내 정전', '블랙아웃'],
    englishDefinition: 'The total sudden loss of electrical power generation and distribution throughout the vessel.',
    difficulty: 'low',
    topic: 'emergency',
  },
  {
    word: 'governor',
    partOfSpeech: '명사',
    meaning: ['조속기'],
    englishDefinition: 'A speed control mechanism that regulates fuel rack injection to maintain constant engine RPM under varying load.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'uninterruptible power supply',
    partOfSpeech: '명사',
    meaning: ['무정전 전원장치', 'UPS'],
    englishDefinition: 'A battery backup system providing continuous instantaneous electric power to critical navigation equipment during blackout.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'earth fault',
    partOfSpeech: '명사',
    meaning: ['지락 사고', '접지 고장'],
    englishDefinition: 'An unintended insulation breakdown connecting an active live conductor directly to the steel ship hull.',
    difficulty: 'high',
    topic: 'engine',
  },
  {
    word: 'megger test',
    partOfSpeech: '명사',
    meaning: ['메거 시험', '절연 저항 시험'],
    englishDefinition: 'A high-voltage diagnostic test using a megohmmeter to measure insulation resistance of motors and cables.',
    difficulty: 'high',
    topic: 'engine',
  },
  {
    word: 'insulation resistance',
    partOfSpeech: '명사',
    meaning: ['절연 저항'],
    englishDefinition: 'The electrical resistance offered by cable insulation jackets to prevent current leakage to the hull.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'unattended machinery space',
    partOfSpeech: '명사',
    meaning: ['무인 당직 기관실', 'UMS'],
    englishDefinition: 'An automated engine room certified to operate safely without watchkeeping engineers present continuously on duty.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'tachometer',
    partOfSpeech: '명사',
    meaning: ['회전계'],
    englishDefinition: 'An instrument indicating the instantaneous rotational speed of an engine shaft in revolutions per minute (RPM).',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'pyrometer',
    partOfSpeech: '명사',
    meaning: ['배기가스 고온계'],
    englishDefinition: 'A thermocouple device used to monitor individual cylinder exhaust gas temperatures.',
    difficulty: 'high',
    topic: 'engine',
  },
  {
    word: 'viscosimeter',
    partOfSpeech: '명사',
    meaning: ['점도계'],
    englishDefinition: 'An inline sensor measuring fuel viscosity to regulate heating for optimal fuel atomization.',
    difficulty: 'high',
    topic: 'engine',
  },
  {
    word: 'salinity indicator',
    partOfSpeech: '명사',
    meaning: ['염분 농도계'],
    englishDefinition: 'An electrical conductivity meter that sounds an alarm and diverts distilled water if salinity exceeds limits.',
    difficulty: 'medium',
    topic: 'engine',
  },

  // --- 9. 당직, 기관 실무 및 운전 지표 (Watchkeeping, Operations & Metrics) ---
  {
    word: 'watch handover',
    partOfSpeech: '명사',
    meaning: ['당직 교대'],
    englishDefinition: 'The formal protocol of transferring navigation or engine room watch responsibilities between officers.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'engine logbook',
    partOfSpeech: '명사',
    meaning: ['기관 일지'],
    englishDefinition: 'The official legal record book in which engine operational readings, bunker quantities, and anomalies are entered.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'malfunction',
    partOfSpeech: '명사',
    meaning: ['작동 불량', '오작동'],
    englishDefinition: 'A failure or abnormal operating state of any machinery or electronic component onboard.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'alarm monitoring system',
    partOfSpeech: '명사',
    meaning: ['경보 감시장치'],
    englishDefinition: 'A centralized automation console that displays visual and acoustic alarms for abnormal vessel pressures or temperatures.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'automatic shutdown',
    partOfSpeech: '명사',
    meaning: ['자동 비상 정지', '트립'],
    englishDefinition: 'An emergency safety trip that immediately cuts off engine fuel during severe hazards like overspeed or low oil pressure.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'slow turning',
    partOfSpeech: '명사',
    meaning: ['저속 턴', '시동 전 회전점검'],
    englishDefinition: 'Turning the main engine slowly with starting air and open indicator cocks prior to startup to verify no liquid leakage in cylinders.',
    difficulty: 'high',
    topic: 'engine',
  },
  {
    word: 'indicator card',
    partOfSpeech: '명사',
    meaning: ['지압도'],
    englishDefinition: 'A pressure-volume diagram recorded from an engine cylinder to evaluate combustion quality and power distribution.',
    difficulty: 'high',
    topic: 'engine',
  },
  {
    word: 'mean effective pressure',
    partOfSpeech: '명사',
    meaning: ['평균 유효 압력', 'MEP'],
    englishDefinition: 'A calculated average theoretical constant pressure acting on the piston to produce the observed engine power output.',
    difficulty: 'high',
    topic: 'engine',
  },
];

export function buildMaritimePhase2Database() {
  // 1. 기존 Phase 1 데이터 로드
  const p1Path = path.resolve('public/data/maritime_smcp_v1.json');
  if (!fs.existsSync(p1Path)) {
    throw new Error(`Phase 1 파일이 존재하지 않습니다: ${p1Path}`);
  }
  const p1Data = JSON.parse(fs.readFileSync(p1Path, 'utf-8'));
  const p1Words: MaritimeWordEntry[] = p1Data.words;
  console.log(`[Phase 1] 기존 SMCP 어휘 수: ${p1Words.length}`);

  // 2. 중복 방지 검사 (Phase 1 ∩ Phase 2 = Ø)
  const p1Set = new Set<string>(p1Words.map((w) => w.word.toLowerCase().trim()));
  const p2Set = new Set<string>();

  for (const item of officerExamWords) {
    const lower = item.word.toLowerCase().trim();
    if (p1Set.has(lower)) {
      throw new Error(`[중복 발견] Phase 1에 이미 존재하는 어휘입니다: ${item.word}`);
    }
    if (p2Set.has(lower)) {
      throw new Error(`[중복 발견] Phase 2 내에서 중복된 어휘입니다: ${item.word}`);
    }
    p2Set.add(lower);
  }
  console.log(`[Phase 2] 신규 해기사 3·4급 어휘 수: ${officerExamWords.length} (중복 0건)`);

  // 3. 통합 어휘 목록 생성 (Phase 1 174어 + Phase 2 180어 = 총 354어)
  const combinedList: MaritimeWordEntry[] = [
    ...p1Words,
    ...officerExamWords.map((item, idx) => ({
      id: p1Words.length + idx + 1,
      ...item,
    })),
  ];

  const database = {
    databaseVersion: 2,
    name: 'IMO SMCP & 해기사 3·4급 빈출 해사영어',
    category: 'maritime_combined',
    phase: 'PHASE_2_OFFICER_EXAM_EXPANSION',
    description: 'IMO SMCP 공식 표준 174어 + 해기사 3급·4급 국가자격시험(항해/기관) 최다 빈출 180어 누적 총 354어 전수 수록 (해경 제외)',
    wordCount: combinedList.length,
    words: combinedList,
  };

  fs.writeFileSync(p1Path, JSON.stringify(database, null, 2), 'utf-8');
  console.log(`[Success] ${p1Path} 파일 갱신 완료! 총 어휘 수: ${combinedList.length}개`);
}

if (process.argv[1] && process.argv[1].includes('generateMaritimePhase2.ts')) {
  buildMaritimePhase2Database();
}
