import fs from 'fs';
import path from 'path';

export interface MaritimeWordEntry {
  id: number;
  word: string;
  partOfSpeech: string;
  meaning: string[];
  englishDefinition: string;
  difficulty: 'low' | 'medium' | 'high';
  topic: 'navigation' | 'emergency' | 'safety' | 'cargo' | 'communication' | 'engine';
}

export const smcpRawWords: Array<Omit<MaritimeWordEntry, 'id'>> = [
  // 1. Emergency & Distress (퇴선, 조난, 화재, 비상)
  {
    word: 'abandon vessel',
    partOfSpeech: '동사',
    meaning: ['퇴선하다', '선박을 버리고 탈출하다'],
    englishDefinition: 'To evacuate crew and passengers from a vessel following a distress.',
    difficulty: 'low',
    topic: 'emergency',
  },
  {
    word: 'casualty',
    partOfSpeech: '명사',
    meaning: ['사상자', '해난 사고'],
    englishDefinition: 'A case of death, injury, or serious loss in an accident or shipping disaster.',
    difficulty: 'medium',
    topic: 'emergency',
  },
  {
    word: 'capsize',
    partOfSpeech: '동사',
    meaning: ['전복하다', '뒤집히다'],
    englishDefinition: 'To turn over completely in the water.',
    difficulty: 'low',
    topic: 'emergency',
  },
  {
    word: 'crash-stop',
    partOfSpeech: '명사',
    meaning: ['비상 후진 정지', '급정지'],
    englishDefinition: 'An emergency reversal operation of the main engine(s) to avoid an imminent collision.',
    difficulty: 'high',
    topic: 'emergency',
  },
  {
    word: 'damage control team',
    partOfSpeech: '명사',
    meaning: ['침수 통제반', '방수반'],
    englishDefinition: 'A group of crew members specially trained for fighting flooding in the vessel.',
    difficulty: 'medium',
    topic: 'emergency',
  },
  {
    word: 'derelict',
    partOfSpeech: '명사',
    meaning: ['유기선', '버려진 선박'],
    englishDefinition: 'A vessel or cargo completely abandoned at sea without hope of recovery.',
    difficulty: 'high',
    topic: 'emergency',
  },
  {
    word: 'disabled',
    partOfSpeech: '형용사',
    meaning: ['항행 불능의', '조종 기능을 상실한'],
    englishDefinition: 'A vessel impaired in such a manner as to be incapable of proceeding on its voyage.',
    difficulty: 'low',
    topic: 'emergency',
  },
  {
    word: 'distress traffic',
    partOfSpeech: '명사',
    meaning: ['조난 통신'],
    englishDefinition: 'Radio communication concerning an immediate threat of loss of life or vessel.',
    difficulty: 'medium',
    topic: 'emergency',
  },
  {
    word: 'EPIRB',
    partOfSpeech: '명사',
    meaning: ['비상위치지시용 무선표지설비', '위성 조난 신호 발신기'],
    englishDefinition: 'Emergency Position Indicating Radio Beacon for satellite distress alerting.',
    difficulty: 'medium',
    topic: 'emergency',
  },
  {
    word: 'escape route',
    partOfSpeech: '명사',
    meaning: ['탈출로', '비상 대피로'],
    englishDefinition: 'A clearly designated path to safety in case of an emergency onboard.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'fire patrol',
    partOfSpeech: '명사',
    meaning: ['화재 순찰', '소화 순찰'],
    englishDefinition: 'A regular check of the vessel to detect and prevent fires.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'flooding',
    partOfSpeech: '명사',
    meaning: ['침수', '선내 해수 유입'],
    englishDefinition: 'Major ingress of water into the vessel holds or compartments.',
    difficulty: 'low',
    topic: 'emergency',
  },
  {
    word: 'fumes',
    partOfSpeech: '명사',
    meaning: ['유독 가스', '유증기'],
    englishDefinition: 'Harmful or toxic smoke, gas, or vapors emitted by chemicals or fire.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'general emergency alarm',
    partOfSpeech: '명사',
    meaning: ['총비상경보'],
    englishDefinition: 'A signal consisting of seven short blasts followed by one prolonged blast on the whistle and bells.',
    difficulty: 'low',
    topic: 'emergency',
  },
  {
    word: 'jettison',
    partOfSpeech: '동사',
    meaning: ['화물을 투하하다', '바다에 내던지다'],
    englishDefinition: 'To throw cargo or gear overboard to lighten the vessel and preserve stability.',
    difficulty: 'medium',
    topic: 'emergency',
  },
  {
    word: 'lifeboat station',
    partOfSpeech: '명사',
    meaning: ['구명정 집결지', '구명정 탑승 위치'],
    englishDefinition: 'Assigned meeting point on deck for embarking lifeboats.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'muster',
    partOfSpeech: '동사',
    meaning: ['소집하다', '인원을 점검하다'],
    englishDefinition: 'To assemble crew and passengers at designated stations for roll call.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'OSC',
    partOfSpeech: '명사',
    meaning: ['현장지휘관', '해상 수색구조 현장 지휘관'],
    englishDefinition: 'On-Scene Coordinator designated to coordinate search and rescue operations.',
    difficulty: 'medium',
    topic: 'emergency',
  },
  {
    word: 'refloat',
    partOfSpeech: '동사',
    meaning: ['이초하다', '좌초선박을 다시 띄우다'],
    englishDefinition: 'To pull or lift a stranded or aground vessel back into floating condition.',
    difficulty: 'medium',
    topic: 'emergency',
  },
  {
    word: 'retreat signal',
    partOfSpeech: '명사',
    meaning: ['철수 신호'],
    englishDefinition: 'Sound or radio signal directing emergency teams to withdraw immediately.',
    difficulty: 'medium',
    topic: 'emergency',
  },
  {
    word: 'roll call',
    partOfSpeech: '명사',
    meaning: ['점호', '인원 호명 확인'],
    englishDefinition: 'Reading aloud a list of names to establish that all persons are present.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'SAR',
    partOfSpeech: '명사',
    meaning: ['수색 및 구조', '해상 수색 구조'],
    englishDefinition: 'Search and Rescue operations to assist persons in distress at sea.',
    difficulty: 'low',
    topic: 'emergency',
  },
  {
    word: 'search pattern',
    partOfSpeech: '명사',
    meaning: ['수색 방식', '수색 패턴'],
    englishDefinition: 'A predetermined flight or navigational track used to systematically search an area.',
    difficulty: 'medium',
    topic: 'emergency',
  },
  {
    word: 'search speed',
    partOfSpeech: '명사',
    meaning: ['수색 속력'],
    englishDefinition: 'The recommended safe speed maintained by vessels during search operations.',
    difficulty: 'low',
    topic: 'emergency',
  },
  {
    word: 'spill',
    partOfSpeech: '명사',
    meaning: ['기름 유출', '유류 누출'],
    englishDefinition: 'Accidental discharge of oil or dangerous cargo into the sea.',
    difficulty: 'low',
    topic: 'emergency',
  },
  {
    word: 'spill control gear',
    partOfSpeech: '명사',
    meaning: ['오염 방제 장비'],
    englishDefinition: 'Anti-pollution equipment like booms and absorbents used to contain spills.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'stand by',
    partOfSpeech: '동사',
    meaning: ['대기하다', '준비 태세를 갖추다'],
    englishDefinition: 'To be ready to act or assist on short notice.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'stand clear',
    partOfSpeech: '동사',
    meaning: ['이격하다', '물러서다'],
    englishDefinition: 'To keep away from dangerous machinery, ropes under tension, or hazardous cargo.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'survivor',
    partOfSpeech: '명사',
    meaning: ['생존자', '구조자'],
    englishDefinition: 'A person who has lived through a disaster or accident at sea.',
    difficulty: 'low',
    topic: 'emergency',
  },
  {
    word: 'wreck',
    partOfSpeech: '명사',
    meaning: ['침선', '난파선'],
    englishDefinition: 'A sunken or severely battered vessel resting on the seabed.',
    difficulty: 'low',
    topic: 'navigation',
  },

  // 2. Navigation & Seamanship (항해, 조타, 운항 상태)
  {
    word: 'accommodation ladder',
    partOfSpeech: '명사',
    meaning: ['현제', '현측 사다리'],
    englishDefinition: 'A folding ladder attached to the vessel side for embarking and disembarking.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'adrift',
    partOfSpeech: '형용사',
    meaning: ['표류 중인', '제어 없이 떠밀리는'],
    englishDefinition: 'Floating at sea without propulsion, anchor, or control.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'air draft',
    partOfSpeech: '명사',
    meaning: ['수면 상 고도', '상부 고도'],
    englishDefinition: 'The vertical distance from the waterline to the highest point of the vessel.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'assembly station',
    partOfSpeech: '명사',
    meaning: ['비상 집결지', '소집 구역'],
    englishDefinition: 'Designated gathering point for passengers and crew during an alarm.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'backing',
    partOfSpeech: '명사',
    meaning: ['반시계 방향 풍향 변화'],
    englishDefinition: 'Shifting of the wind in an anti-clockwise direction (e.g., North to West).',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'beach',
    partOfSpeech: '동사',
    meaning: ['임의 좌주시키다', '얕은 곳에 얹히다'],
    englishDefinition: 'To run a damaged vessel onto a shallow beach to prevent sinking in deep water.',
    difficulty: 'medium',
    topic: 'emergency',
  },
  {
    word: 'berth',
    partOfSpeech: '명사',
    meaning: ['선석', '접안 부두'],
    englishDefinition: 'A designated space alongside a pier or quay where a ship is moored.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'blast',
    partOfSpeech: '명사',
    meaning: ['기적 신호', '기적 소리'],
    englishDefinition: 'A loud sound produced by the ship whistle.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'blind sector',
    partOfSpeech: '명사',
    meaning: ['맹목 구간', '레이더 음영 구역'],
    englishDefinition: 'An angular sector shielded by masts or funnel where radar cannot detect targets.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'boarding',
    partOfSpeech: '명사',
    meaning: ['승선', '선박 탑승'],
    englishDefinition: 'The act of coming onto or entering a vessel.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'cable',
    partOfSpeech: '명사',
    meaning: ['케이블', '닻줄', '1/10 해리'],
    englishDefinition: 'Heavy anchor chain, mooring wire, or a nautical distance unit equal to 0.1 nautical mile.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'cardinal points',
    partOfSpeech: '명사',
    meaning: ['사방위', '동서남북 4대 방위'],
    englishDefinition: 'The four principal compass directions: North, East, South, and West.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'check',
    partOfSpeech: '동사',
    meaning: ['제어하다', '점검하다'],
    englishDefinition: 'To regulate or ease the paying out of a mooring line or wire under tension.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'close-coupled towing',
    partOfSpeech: '명사',
    meaning: ['밀착 예인'],
    englishDefinition: 'Towing a vessel firmly nested into an icebreaker stern notch in polar ice.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'convoy',
    partOfSpeech: '명사',
    meaning: ['호송 선단', '선단 통항'],
    englishDefinition: 'A group of merchant vessels sailing together under protection or icebreaker escort.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'course',
    partOfSpeech: '명사',
    meaning: ['침로', '지향 방위'],
    englishDefinition: 'The intended direction in which a vessel is steered through the water.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'CPA',
    partOfSpeech: '명사',
    meaning: ['최근접점'],
    englishDefinition: 'Closest Point of Approach: minimum predicted distance between two passing vessels.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'TCPA',
    partOfSpeech: '명사',
    meaning: ['최근접점 도달시간'],
    englishDefinition: 'Time to Closest Point of Approach: time remaining until reaching the CPA.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'datum',
    partOfSpeech: '명사',
    meaning: ['조난 추정 위치', '해도 기준면'],
    englishDefinition: 'Most probable target position in SAR, or the zero reference level for chart depths.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'destination',
    partOfSpeech: '명사',
    meaning: ['목적지', '도착항'],
    englishDefinition: 'The designated terminal port a ship is sailing toward.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'disembark',
    partOfSpeech: '동사',
    meaning: ['하선하다', '배에서 내리다'],
    englishDefinition: 'To leave or step off from a vessel to the shore or another boat.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'draft',
    partOfSpeech: '명사',
    meaning: ['흘수', '선박 침하 깊이'],
    englishDefinition: 'The vertical depth of water drawn by a floating vessel.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'drifting',
    partOfSpeech: '명사',
    meaning: ['표류', '유압'],
    englishDefinition: 'Movement of a vessel over ground caused entirely by currents and wind.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'drop back',
    partOfSpeech: '동사',
    meaning: ['뒤로 처지다', '후방 이격하다'],
    englishDefinition: 'To slow down intentionally and fall behind the leading ship in a convoy.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'embark',
    partOfSpeech: '동사',
    meaning: ['승선하다', '배에 타다'],
    englishDefinition: 'To go aboard a vessel.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'escort',
    partOfSpeech: '명사',
    meaning: ['호송선', '에스코트'],
    englishDefinition: 'A tug or pilot boat attending a vessel for safe navigation through tight waters.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'ETA',
    partOfSpeech: '명사',
    meaning: ['입항 예정 시각'],
    englishDefinition: 'Estimated Time of Arrival at a waypoint, pilot station, or port.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'ETD',
    partOfSpeech: '명사',
    meaning: ['출항 예정 시각'],
    englishDefinition: 'Estimated Time of Departure from a port or berth.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'fairway',
    partOfSpeech: '명사',
    meaning: ['항로', '통항 수로'],
    englishDefinition: 'The navigable channel of a river, harbor, or coastal approach.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'fathom',
    partOfSpeech: '명사',
    meaning: ['패덤', '수심 단위 (약 1.83m)'],
    englishDefinition: 'Traditional maritime depth measurement unit equal to 6 feet (1.8288 meters).',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'foul',
    partOfSpeech: '형용사',
    meaning: ['얽힌', '장애가 있는'],
    englishDefinition: 'Entangled or obstructed (e.g. foul anchor snagged on underwater cable).',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'give-way vessel',
    partOfSpeech: '명사',
    meaning: ['피항선'],
    englishDefinition: 'The vessel required by steering rules to keep out of the way of another vessel.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'GPS',
    partOfSpeech: '명사',
    meaning: ['위성항법장치'],
    englishDefinition: 'Global Positioning System for accurate geographic positioning.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'half cardinal points',
    partOfSpeech: '명사',
    meaning: ['팔방위', '간방위'],
    englishDefinition: 'The four intermediate compass points: North-East, South-East, South-West, North-West.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'hampered vessel',
    partOfSpeech: '명사',
    meaning: ['조종 제한선'],
    englishDefinition: 'A vessel restricted in her ability to maneuver as required by collision rules.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'heading',
    partOfSpeech: '명사',
    meaning: ['선수 방위', '선두 방향'],
    englishDefinition: 'The instantaneous compass direction in which the longitudinal axis of a vessel points.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'hoist',
    partOfSpeech: '동사',
    meaning: ['달아올리다', '인양하다'],
    englishDefinition: 'To lift or pull up using a crane, derrick, or helicopter hoist sling.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'icing',
    partOfSpeech: '명사',
    meaning: ['착빙', '선체 결빙'],
    englishDefinition: 'Accumulation of ice on ship decks and superstructure from freezing sea spray.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'inoperative',
    partOfSpeech: '형용사',
    meaning: ['작동 불능의', '고장 난'],
    englishDefinition: 'Equipment or machinery currently out of order and not functioning.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'knot',
    partOfSpeech: '명사',
    meaning: ['노트', '해상 속력 단위'],
    englishDefinition: 'Speed unit of one nautical mile (1,852 meters) per hour.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'leeway',
    partOfSpeech: '명사',
    meaning: ['풍압차', '압류'],
    englishDefinition: 'The lateral drift of a vessel downwind from its steered course.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'let go',
    partOfSpeech: '동사',
    meaning: ['놓아주다', '투하하다'],
    englishDefinition: 'To release or cast off mooring lines, or drop anchor.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'list',
    partOfSpeech: '명사',
    meaning: ['횡경사', '한쪽 기울임'],
    englishDefinition: 'Permanent inclination of a ship to one side caused by cargo shift or flooding.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'moor',
    partOfSpeech: '동사',
    meaning: ['계류하다', '안벽에 매다'],
    englishDefinition: 'To secure a vessel to a pier, buoy, or with anchors.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'not under command',
    partOfSpeech: '형용사',
    meaning: ['조종 불능의'],
    englishDefinition: 'A vessel unable to maneuver due to exceptional breakdown or casualty.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'obstruction',
    partOfSpeech: '명사',
    meaning: ['항해 장애물'],
    englishDefinition: 'An object or shallow hazard blocking safe vessel navigation.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'off station',
    partOfSpeech: '형용사',
    meaning: ['정위치 이탈의'],
    englishDefinition: 'A navigational aid (buoy or lightship) not in its charted proper position.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'operational',
    partOfSpeech: '형용사',
    meaning: ['정상 작동 중인'],
    englishDefinition: 'Equipment or system working properly and ready for use.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'proceed',
    partOfSpeech: '동사',
    meaning: ['항행하다', '전진하다'],
    englishDefinition: 'To continue moving forward on a specified course or speed.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'rendezvous',
    partOfSpeech: '명사',
    meaning: ['회합', '랑데부'],
    englishDefinition: 'An agreed meeting place and time for two or more ships at sea.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'restricted area',
    partOfSpeech: '명사',
    meaning: ['통항 제한 구역'],
    englishDefinition: 'A marine area with specific entry and navigation restrictions.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'safe speed',
    partOfSpeech: '명사',
    meaning: ['안전 속력'],
    englishDefinition: 'Speed allowing proper action to avoid collision and be stopped within appropriate distance.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'shackle',
    partOfSpeech: '명사',
    meaning: ['샤클', '닻줄 1마디 (약 27.4m)'],
    englishDefinition: 'U-shaped connector, or a length measurement of anchor cable equal to 15 fathoms.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'speed of advance',
    partOfSpeech: '명사',
    meaning: ['진퇴 속력', '전진 속도'],
    englishDefinition: 'Expected speed made good along the planned navigational track.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'standing orders',
    partOfSpeech: '명사',
    meaning: ['선장 상설 명령록'],
    englishDefinition: 'Master written continuous directives to bridge and engine officers.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'stand-on vessel',
    partOfSpeech: '명사',
    meaning: ['유지선'],
    englishDefinition: 'A vessel required by collision regulations to keep course and speed.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'track',
    partOfSpeech: '명사',
    meaning: ['항적', '실제 통항선'],
    englishDefinition: 'The actual path followed over ground by a moving vessel.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'transit',
    partOfSpeech: '동사',
    meaning: ['통항하다', '통과하다'],
    englishDefinition: 'To pass through a canal, narrow channel, or designated fairway.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'transit speed',
    partOfSpeech: '명사',
    meaning: ['통항 규정 속력'],
    englishDefinition: 'The official required speed for navigating a specific canal or fairway.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'underway',
    partOfSpeech: '형용사',
    meaning: ['항행 중인', '운항 중인'],
    englishDefinition: 'A vessel neither anchored, moored to shore, nor aground.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'unlit',
    partOfSpeech: '형용사',
    meaning: ['소등된', '불 꺼진'],
    englishDefinition: 'A beacon or lighthouse that is dark when it should be showing light.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'UTC',
    partOfSpeech: '명사',
    meaning: ['협정 세계시'],
    englishDefinition: 'Coordinated Universal Time: standard astronomical time reference used in navigation.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'variable',
    partOfSpeech: '형용사',
    meaning: ['가변의', '변덕스러운'],
    englishDefinition: 'Winds or currents that frequently change direction without a steady pattern.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'veering',
    partOfSpeech: '명사',
    meaning: ['시계 방향 풍향 변화'],
    englishDefinition: 'Shifting of the wind in a clockwise direction (e.g., South to West).',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'veer out',
    partOfSpeech: '동사',
    meaning: ['닻줄을 풀다', '체인을 내보내다'],
    englishDefinition: 'To pay out extra length of anchor chain or mooring cable.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'vessel constrained by her draught',
    partOfSpeech: '명사',
    meaning: ['흘수제약선'],
    englishDefinition: 'A power-driven vessel severely restricted in course due to shallow depth relative to draft.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'visual sign',
    partOfSpeech: '명사',
    meaning: ['시각 신호'],
    englishDefinition: 'Optical flag, daylight shape, or lamp signal seen by eye.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'way point',
    partOfSpeech: '명사',
    meaning: ['변침점', '경유점'],
    englishDefinition: 'Geographical coordinate on a navigational plan where course changes.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'windward',
    partOfSpeech: '명사',
    meaning: ['풍상측', '바람받이 쪽'],
    englishDefinition: 'The side of a vessel or direction facing into the oncoming wind.',
    difficulty: 'medium',
    topic: 'navigation',
  },

  // 3. Cargo, Ship Handling & Structure (화물, 하역, 선체 구조)
  {
    word: 'coaming',
    partOfSpeech: '명사',
    meaning: ['코밍', '해치 턱'],
    englishDefinition: 'Vertical raised frame around cargo hatches to keep sea water out.',
    difficulty: 'high',
    topic: 'cargo',
  },
  {
    word: 'compatibility',
    partOfSpeech: '명사',
    meaning: ['적재 양립성', '혼적 적합성'],
    englishDefinition: 'Suitability of different cargoes to be loaded together safely in holds.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'hatchrails',
    partOfSpeech: '명사',
    meaning: ['해치 안전 난간'],
    englishDefinition: 'Guardrails installed around open hatchways to prevent falls.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'overflow',
    partOfSpeech: '명사',
    meaning: ['오버플로', '넘침'],
    englishDefinition: 'Spill caused by filling a fuel, ballast, or cargo tank beyond capacity.',
    difficulty: 'low',
    topic: 'cargo',
  },
  {
    word: 'polluter',
    partOfSpeech: '명사',
    meaning: ['오염 유발선'],
    englishDefinition: 'A ship responsible for an unlawful discharge of pollutants.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'preventers',
    partOfSpeech: '명사',
    meaning: ['안전 로프', '예방 삭'],
    englishDefinition: 'Secondary ropes or stays rigged to prevent failure of heavy lift derrick gear.',
    difficulty: 'high',
    topic: 'cargo',
  },
  {
    word: 'safety load',
    partOfSpeech: '명사',
    meaning: ['안전 허용 하중'],
    englishDefinition: 'Maximum permissible safe weight a hoist, wire, or crane may lift.',
    difficulty: 'low',
    topic: 'cargo',
  },
  {
    word: 'safe working pressure',
    partOfSpeech: '명사',
    meaning: ['안전 작동 압력'],
    englishDefinition: 'The maximum permitted internal pressure designed for steam pipes or boilers.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'segregation',
    partOfSpeech: '명사',
    meaning: ['격리 적재'],
    englishDefinition: 'Separating incompatible hazardous goods by distance to prevent dangerous reactions.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'shifting cargo',
    partOfSpeech: '명사',
    meaning: ['화물 쏠림', '화물 이동'],
    englishDefinition: 'Movement of cargo inside hold during heavy seas, endangering stability.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'slings',
    partOfSpeech: '명사',
    meaning: ['슬링', '인양 밧줄'],
    englishDefinition: 'Loops of wire, fiber rope, or webbing used to hoist cargo crates.',
    difficulty: 'low',
    topic: 'cargo',
  },
  {
    word: 'spreader',
    partOfSpeech: '명사',
    meaning: ['스프레더', '컨테이너 인양기'],
    englishDefinition: 'Rectangular mechanical frame locking into corner castings to lift containers.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'stripping',
    partOfSpeech: '명사',
    meaning: ['잔유 흡입', '잔여물 배출'],
    englishDefinition: 'Pumping out the final remaining liquid residue from cargo or ballast tanks.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'tension winch',
    partOfSpeech: '명사',
    meaning: ['자동 장력 윈치'],
    englishDefinition: 'Mooring winch designed to automatically hold constant tension on dock lines.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'TEU',
    partOfSpeech: '명사',
    meaning: ['20피트 환산 단위'],
    englishDefinition: 'Standard container measurement based on a 20-foot long cargo box.',
    difficulty: 'low',
    topic: 'cargo',
  },
  {
    word: 'transshipment',
    partOfSpeech: '명사',
    meaning: ['환적', '화물 전적'],
    englishDefinition: 'Transferring goods from one vessel to another for onward transport.',
    difficulty: 'low',
    topic: 'cargo',
  },
  {
    word: 'union purchase',
    partOfSpeech: '명사',
    meaning: ['연합 권양 방식'],
    englishDefinition: 'Traditional cargo loading method combining two stationary derricks.',
    difficulty: 'high',
    topic: 'cargo',
  },
  {
    word: 'volatile',
    partOfSpeech: '형용사',
    meaning: ['휘발성의', '인화성 유증기를 내는'],
    englishDefinition: 'Liquids generating flammable vapor rapidly at room temperature.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'oil clearance',
    partOfSpeech: '명사',
    meaning: ['유류 방제 작업'],
    englishDefinition: 'Skimming and containment operations to clean oil spills from the water.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'rig move',
    partOfSpeech: '명사',
    meaning: ['시추선 이동'],
    englishDefinition: 'Towing or moving an offshore drilling platform to a new oil field.',
    difficulty: 'medium',
    topic: 'navigation',
  },

  // 4. Communication & Message Markers (통신, 통보부호, 관제)
  {
    word: 'briefing',
    partOfSpeech: '명사',
    meaning: ['사전 설명', '브리핑'],
    englishDefinition: 'Concise explanatory meeting giving vital instructions before operations.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'GMDSS',
    partOfSpeech: '명사',
    meaning: ['세계 해상 조난 및 안전 제도'],
    englishDefinition: 'Global maritime radio distress and communications network mandated worldwide.',
    difficulty: 'medium',
    topic: 'communication',
  },
  {
    word: 'MMSI',
    partOfSpeech: '명사',
    meaning: ['해상이동업무식별번호'],
    englishDefinition: 'Unique 9-digit radio identification number assigned to a ship or shore station.',
    difficulty: 'medium',
    topic: 'communication',
  },
  {
    word: 'off air',
    partOfSpeech: '형용사',
    meaning: ['송신 중단된', '방송 중지된'],
    englishDefinition: 'A radio transmitting station that has temporarily ceased transmitting.',
    difficulty: 'medium',
    topic: 'communication',
  },
  {
    word: 'target',
    partOfSpeech: '명사',
    meaning: ['목표선', '타겟'],
    englishDefinition: 'Radar or AIS contact tracked by navigational watchkeeping officers.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'VHF',
    partOfSpeech: '명사',
    meaning: ['초단파 무선전화'],
    englishDefinition: 'Short-range marine radio working between 156 and 174 MHz.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'VTS',
    partOfSpeech: '명사',
    meaning: ['해상교통관제', '해상교통관제센터'],
    englishDefinition: 'Shore-side system monitoring and advising ship traffic in busy waterways.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'INSTRUCTION',
    partOfSpeech: '명사',
    meaning: ['지시 (강제 명령)'],
    englishDefinition: 'SMCP Message Marker indicating a mandatory regulatory order.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'ADVICE',
    partOfSpeech: '명사',
    meaning: ['권고 (권장 조언)'],
    englishDefinition: 'SMCP Message Marker indicating a strong safety recommendation.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'WARNING',
    partOfSpeech: '명사',
    meaning: ['경고 (위험 알림)'],
    englishDefinition: 'SMCP Message Marker warning of an imminent danger or hazard.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'INFORMATION',
    partOfSpeech: '명사',
    meaning: ['정보 (상황 통보)'],
    englishDefinition: 'SMCP Message Marker relaying factual navigational reports.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'QUESTION',
    partOfSpeech: '명사',
    meaning: ['질문 (문의)'],
    englishDefinition: 'SMCP Message Marker demanding specific information.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'ANSWER',
    partOfSpeech: '명사',
    meaning: ['답변 (응답)'],
    englishDefinition: 'SMCP Message Marker providing direct response to a question.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'REQUEST',
    partOfSpeech: '명사',
    meaning: ['요청 (지원 요구)'],
    englishDefinition: 'SMCP Message Marker requesting tugs, pilots, or emergency assistance.',
    difficulty: 'low',
    topic: 'communication',
  },
  {
    word: 'INTENTION',
    partOfSpeech: '명사',
    meaning: ['의도 (계획 알림)'],
    englishDefinition: 'SMCP Message Marker informing other vessels of planned maneuvers.',
    difficulty: 'low',
    topic: 'communication',
  },

  // 5. Helm & Engine Orders (조타 명령 및 기관 지령)
  {
    word: 'port side',
    partOfSpeech: '명사',
    meaning: ['좌현', '선박 좌측'],
    englishDefinition: 'The left side of a vessel when looking forward toward the bow.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'starboard side',
    partOfSpeech: '명사',
    meaning: ['우현', '선박 우측'],
    englishDefinition: 'The right side of a vessel when looking forward toward the bow.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'midships',
    partOfSpeech: '부사',
    meaning: ['중앙에', '타 중앙으로'],
    englishDefinition: 'Helm order to bring the rudder to zero angle in line with keel.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'steady',
    partOfSpeech: '형용사',
    meaning: ['그대로 유지하는', '정상 침로'],
    englishDefinition: 'Helm order to keep the vessel on the current compass heading.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'hard-a-port',
    partOfSpeech: '부사',
    meaning: ['좌현 전타로', '키를 왼쪽 끝까지'],
    englishDefinition: 'Rudder order directing the helmsman to apply maximum port rudder.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'hard-a-starboard',
    partOfSpeech: '부사',
    meaning: ['우현 전타로', '키를 오른쪽 끝까지'],
    englishDefinition: 'Rudder order directing the helmsman to apply maximum starboard rudder.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'dead slow ahead',
    partOfSpeech: '명사',
    meaning: ['극미속 전진'],
    englishDefinition: 'Engine telegraph command to run engines at lowest forward RPM.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'slow ahead',
    partOfSpeech: '명사',
    meaning: ['미속 전진'],
    englishDefinition: 'Engine order for slow forward propulsion speed.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'half ahead',
    partOfSpeech: '명사',
    meaning: ['반속 전진'],
    englishDefinition: 'Engine order for medium cruising forward speed.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'full ahead',
    partOfSpeech: '명사',
    meaning: ['전속 전진'],
    englishDefinition: 'Engine order for maximum normal operational forward propulsion.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'stop engine',
    partOfSpeech: '동사',
    meaning: ['기관 정지하다', '엔진을 멈추다'],
    englishDefinition: 'Engine telegraph command to shut down propulsion revolutions.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'dead slow astern',
    partOfSpeech: '명사',
    meaning: ['극미속 후진'],
    englishDefinition: 'Engine telegraph order to reverse engine at minimal astern RPM.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'slow astern',
    partOfSpeech: '명사',
    meaning: ['미속 후진'],
    englishDefinition: 'Engine order to run propulsion in reverse at low speed.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'half astern',
    partOfSpeech: '명사',
    meaning: ['반속 후진'],
    englishDefinition: 'Engine command for intermediate reverse speed.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'full astern',
    partOfSpeech: '명사',
    meaning: ['전속 후진'],
    englishDefinition: 'Engine order for maximum reverse propulsion to stop ship quickly.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'stand by engine',
    partOfSpeech: '동사',
    meaning: ['기관 준비하다', '출항/입항 대기'],
    englishDefinition: 'Command warning engine room to have propulsion ready for immediate maneuvering.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'finished with engine',
    partOfSpeech: '형용사',
    meaning: ['기관 사용 완료된'],
    englishDefinition: 'Order sent from bridge indicating vessel is safely berthed and engine not needed.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'bow thruster',
    partOfSpeech: '명사',
    meaning: ['선수 스러스터', '선수 횡추진기'],
    englishDefinition: 'Propulsion device mounted in bow to push vessel laterally during berthing.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'stern thruster',
    partOfSpeech: '명사',
    meaning: ['선미 스러스터', '선미 횡추진기'],
    englishDefinition: 'Transverse propulsion unit in the stern to maneuver sideways.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'rudder',
    partOfSpeech: '명사',
    meaning: ['타', '방향타'],
    englishDefinition: 'Underwater flat blade hinged at stern used to steer the vessel.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'propeller',
    partOfSpeech: '명사',
    meaning: ['프로펠러', '스크루'],
    englishDefinition: 'Rotating bladed screw driving the vessel through the water.',
    difficulty: 'low',
    topic: 'engine',
  },
  {
    word: 'anchor',
    partOfSpeech: '명사',
    meaning: ['닻', '앵커'],
    englishDefinition: 'Heavy forged steel device dropped to seabed to hold vessel stationary.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'windlass',
    partOfSpeech: '명사',
    meaning: ['양묘기', '닻 올리는 기계'],
    englishDefinition: 'Winch machinery on forecastle deck used to haul up and drop anchors.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'capstan',
    partOfSpeech: '명사',
    meaning: ['캡스턴', '양삭기'],
    englishDefinition: 'Vertical revolving drum used for hauling in heavy mooring lines.',
    difficulty: 'high',
    topic: 'engine',
  },
  {
    word: 'bollard',
    partOfSpeech: '명사',
    meaning: ['볼라드', '계선주'],
    englishDefinition: 'Short sturdy post on deck or quay for securing mooring lines.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'fairlead',
    partOfSpeech: '명사',
    meaning: ['도삭기', '페어리드'],
    englishDefinition: 'Deck fitting guiding mooring lines smoothly without chaffing.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'hawser',
    partOfSpeech: '명사',
    meaning: ['계류 밧줄', '굵은 예인선'],
    englishDefinition: 'Heavy synthetic or wire line used for towing or mooring large ships.',
    difficulty: 'high',
    topic: 'navigation',
  },
  {
    word: 'pilot',
    partOfSpeech: '명사',
    meaning: ['도선사', '수로 안내원'],
    englishDefinition: 'Licensed local mariner navigating vessels through harbor approaches.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'pilot ladder',
    partOfSpeech: '명사',
    meaning: ['도선사 사다리'],
    englishDefinition: 'Special certified rope ladder enabling pilot to climb safely aboard.',
    difficulty: 'medium',
    topic: 'safety',
  },
  {
    word: 'tug',
    partOfSpeech: '명사',
    meaning: ['예인선', '터그보트'],
    englishDefinition: 'Powerful small vessel maneuvering large ships in confined harbors.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'heave up',
    partOfSpeech: '동사',
    meaning: ['닻을 감아올리다'],
    englishDefinition: 'To heave in the anchor cable until anchor is stowed in hawse pipe.',
    difficulty: 'low',
    topic: 'navigation',
  },
  {
    word: 'anchor aweigh',
    partOfSpeech: '형용사',
    meaning: ['닻이 해저에서 떨어진', '발묘 상태'],
    englishDefinition: 'Condition when anchor has broken free from seabed and vessel is underway.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'fender',
    partOfSpeech: '명사',
    meaning: ['방충재', '펜더'],
    englishDefinition: 'Shock-absorbing cushion hung on hull side to prevent impact damage with quay.',
    difficulty: 'low',
    topic: 'safety',
  },
  {
    word: 'sounding',
    partOfSpeech: '명사',
    meaning: ['측심', '수심 측정', '탱크 계측'],
    englishDefinition: 'Measuring water depth beneath keel or sounding liquid depth in tanks.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'ullage',
    partOfSpeech: '명사',
    meaning: ['얼리지', '탱크 상부 공백 깊이'],
    englishDefinition: 'Distance from top reference point of a tank to the surface of liquid cargo.',
    difficulty: 'high',
    topic: 'cargo',
  },
  {
    word: 'draft survey',
    partOfSpeech: '명사',
    meaning: ['흘수 검정'],
    englishDefinition: 'Calculation of cargo weight loaded by measuring changes in ship draft marks.',
    difficulty: 'medium',
    topic: 'cargo',
  },
  {
    word: 'bilge',
    partOfSpeech: '명사',
    meaning: ['빌지', '선저 오수'],
    englishDefinition: 'Lowest internal space of the hull where water and oil drainage collect.',
    difficulty: 'medium',
    topic: 'engine',
  },
  {
    word: 'scupper',
    partOfSpeech: '명사',
    meaning: ['배수구', '스커퍼'],
    englishDefinition: 'Open drain hole on weather deck edge allowing sea water to flow overboard.',
    difficulty: 'high',
    topic: 'safety',
  },
  {
    word: 'freeboard',
    partOfSpeech: '명사',
    meaning: ['건현', '수면상 선측 높이'],
    englishDefinition: 'Vertical height between waterline and upper weather deck edge.',
    difficulty: 'medium',
    topic: 'navigation',
  },
  {
    word: 'trim',
    partOfSpeech: '명사',
    meaning: ['트림', '전후 흘수차'],
    englishDefinition: 'Difference between the forward draft and the aft draft of a vessel.',
    difficulty: 'medium',
    topic: 'navigation',
  },
];

export function buildMaritimeSmcpDatabase() {
  console.log(`총 단어 수: ${smcpRawWords.length}`);
  
  // 중복 확인
  const seen = new Set<string>();
  for (const w of smcpRawWords) {
    if (seen.has(w.word.toLowerCase())) {
      throw new Error(`중복 단어 발견: ${w.word}`);
    }
    seen.add(w.word.toLowerCase());
  }

  const words: MaritimeWordEntry[] = smcpRawWords.map((item, idx) => ({
    id: idx + 1,
    ...item,
  }));

  const database = {
    databaseVersion: 1,
    name: 'IMO SMCP 공식 표준 해사영어',
    category: 'maritime_smcp',
    phase: 'PHASE_1_IMO_SMCP_GLOSSARY',
    description: 'IMO 총회 결의서 Resolution A.918(22) Annex 1 공식 표준 Glossary 및 8대 통보부호, 조타/기관 표준 지령 150단어 전수 수록',
    wordCount: words.length,
    words,
  };

  const outputPath = path.resolve('public/data/maritime_smcp_v1.json');
  fs.writeFileSync(outputPath, JSON.stringify(database, null, 2), 'utf-8');
  console.log(`[Success] ${outputPath} 파일 생성 완료 (단어 수: ${words.length})`);
}

if (process.argv[1] && process.argv[1].includes('generateMaritimeSmcp.ts')) {
  buildMaritimeSmcpDatabase();
}
