const fs = require('fs');
const path = require('path');

// 1. 🌱 기초 (Basic): 히라가나/가타카나 읽기 & 기본 인사말, 숫자, 일상 기초 어휘
const basicWords = [
  // 인사말 & 기본 회화 표현
  { word: "こんにちは", meaning: ["안녕하세요 (낮 인사)"], partOfSpeech: "표현", difficulty: "low", topic: "basic" },
  { word: "おはよう", meaning: ["좋은 아침 (아침 인사)", "안녕"], partOfSpeech: "표현", difficulty: "low", topic: "basic" },
  { word: "こんばんは", meaning: ["안녕하세요 (저녁 인사)"], partOfSpeech: "표현", difficulty: "low", topic: "basic" },
  { word: "さようなら", meaning: ["안녕히 가세요", "작별 인사"], partOfSpeech: "표현", difficulty: "low", topic: "basic" },
  { word: "ありがとう", meaning: ["고마워요", "감사합니다"], partOfSpeech: "표현", difficulty: "low", topic: "basic" },
  { word: "どうも", meaning: ["고마워요", "왠지", "정말"], partOfSpeech: "부사", difficulty: "low", topic: "basic" },
  { word: "すみません", meaning: ["죄송합니다", "실례합니다", "저기요"], partOfSpeech: "표현", difficulty: "low", topic: "basic" },
  { word: "ごめんなさい", meaning: ["미안합니다", "죄송해요"], partOfSpeech: "표현", difficulty: "low", topic: "basic" },
  { word: "はい", meaning: ["네", "예"], partOfSpeech: "감탄사", difficulty: "low", topic: "basic" },
  { word: "いいえ", meaning: ["아니요", "아닙니다"], partOfSpeech: "감탄사", difficulty: "low", topic: "basic" },
  { word: "はじめまして", meaning: ["처음 뵙겠습니다"], partOfSpeech: "표현", difficulty: "low", topic: "basic" },
  { word: "どうぞ", meaning: ["부디", "어서", "여기요"], partOfSpeech: "부사", difficulty: "low", topic: "basic" },
  { word: "いただきます", meaning: ["잘 먹겠습니다"], partOfSpeech: "표현", difficulty: "low", topic: "basic" },
  { word: "ごちそうさま", meaning: ["잘 먹었습니다"], partOfSpeech: "표현", difficulty: "low", topic: "basic" },
  { word: "おねがいします", meaning: ["부탁합니다"], partOfSpeech: "표현", difficulty: "low", topic: "basic" },
  { word: "じゃあね", meaning: ["그럼 또 봐", "안녕"], partOfSpeech: "표현", difficulty: "low", topic: "basic" },
  
  // 숫자
  { word: "一 (いち)", meaning: ["숫자 1", "하나"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "二 (に)", meaning: ["숫자 2", "둘"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "三 (さん)", meaning: ["숫자 3", "셋"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "四 (よん)", meaning: ["숫자 4", "넷"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "五 (ご)", meaning: ["숫자 5", "다섯"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "六 (ろく)", meaning: ["숫자 6", "여섯"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "七 (なな)", meaning: ["숫자 7", "일곱"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "八 (はち)", meaning: ["숫자 8", "여덟"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "九 (きゅう)", meaning: ["숫자 9", "아홉"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "十 (じゅう)", meaning: ["숫자 10", "열"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "百 (ひゃく)", meaning: ["숫자 100", "백"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "千 (せん)", meaning: ["숫자 1000", "천"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "万 (まん)", meaning: ["숫자 10000", "만"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },

  // 사람 및 대명사
  { word: "私 (わたし)", meaning: ["나", "저"], partOfSpeech: "대명사", difficulty: "low", topic: "basic" },
  { word: "あなた", meaning: ["당신", "너"], partOfSpeech: "대명사", difficulty: "low", topic: "basic" },
  { word: "彼 (かれ)", meaning: ["그", "남자친구"], partOfSpeech: "대명사", difficulty: "low", topic: "basic" },
  { word: "彼女 (かのじょ)", meaning: ["그녀", "여자친구"], partOfSpeech: "대명사", difficulty: "low", topic: "basic" },
  { word: "人 (ひと)", meaning: ["사람"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "友達 (ともだち)", meaning: ["친구"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "家族 (かぞく)", meaning: ["가족"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "名前 (なまえ)", meaning: ["이름"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },

  // 기초 일상 사물 & 자연
  { word: "水 (みず)", meaning: ["물"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "お茶 (おちゃ)", meaning: ["차", "녹차"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "ご飯 (ごはん)", meaning: ["밥", "식사"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "パン", meaning: ["빵"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "肉 (にく)", meaning: ["고기"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "魚 (さかな)", meaning: ["생선", "물고기"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "本 (ほん)", meaning: ["책"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "机 (つくえ)", meaning: ["책상"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "椅子 (いす)", meaning: ["의자"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "犬 (いぬ)", meaning: ["개", "강아지"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "猫 (ねこ)", meaning: ["고양이"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "車 (くるま)", meaning: ["자동차", "차"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "電車 (でんしゃ)", meaning: ["전철", "기차"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "家 (いえ)", meaning: ["집"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "部屋 (へや)", meaning: ["방"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "山 (やま)", meaning: ["산"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "川 (かわ)", meaning: ["강"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "空 (そら)", meaning: ["하늘"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "雨 (あめ)", meaning: ["비"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "雪 (ゆき)", meaning: ["눈 (날씨)"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "花 (はな)", meaning: ["꽃"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "手 (て)", meaning: ["손"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "目 (め)", meaning: ["눈 (신체)"], partOfSpeech: "명사", difficulty: "low", topic: "basic" },
  { word: "口 (くち)", meaning: ["입"], partOfSpeech: "명사", difficulty: "low", topic: "basic" }
];

// 2. 🥉 N5: JLPT N5 공식 빈출 어휘 (학교, 시간, 기초 동사/형용사)
const n5Words = [
  { word: "学生 (がくせい)", meaning: ["학생"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "先生 (せんせい)", meaning: ["선생님", "교사"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "学校 (がっこう)", meaning: ["학교"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "教室 (きょうしつ)", meaning: ["교실"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "会社 (かいしゃ)", meaning: ["회사"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "病院 (びょういん)", meaning: ["병원"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "駅 (えき)", meaning: ["기차역", "역"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "銀行 (ぎんこう)", meaning: ["은행"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "店 (みせ)", meaning: ["가게", "매장"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "時間 (じかん)", meaning: ["시간"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "時計 (とけい)", meaning: ["시계"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "今日 (きょう)", meaning: ["오늘"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "明日 (あした)", meaning: ["내일"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "昨日 (きのう)", meaning: ["어제"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "今 (いま)", meaning: ["지금", "현재"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "朝 (あさ)", meaning: ["아침"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "昼 (ひる)", meaning: ["낮", "점심"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "夜 (よる)", meaning: ["밤", "저녁"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "毎日 (まいにち)", meaning: ["매일", "날마다"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "勉強 (べんきょう)", meaning: ["공부", "학습"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "仕事 (しごと)", meaning: ["일", "직업"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "電話 (でんわ)", meaning: ["전화"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "写真 (しゃしん)", meaning: ["사진"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "手紙 (てがみ)", meaning: ["편지"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "映画 (えいが)", meaning: ["영화"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "音楽 (おんがく)", meaning: ["음악"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "旅行 (りょこう)", meaning: ["여행"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "食べる (たべる)", meaning: ["먹다"], partOfSpeech: "동사", difficulty: "low", topic: "jlpt_n5" },
  { word: "飲む (のむ)", meaning: ["마시다"], partOfSpeech: "동사", difficulty: "low", topic: "jlpt_n5" },
  { word: "見る (みる)", meaning: ["보다"], partOfSpeech: "동사", difficulty: "low", topic: "jlpt_n5" },
  { word: "聞く (きく)", meaning: ["듣다", "묻다"], partOfSpeech: "동사", difficulty: "low", topic: "jlpt_n5" },
  { word: "話す (はなす)", meaning: ["말하다", "이야기하다"], partOfSpeech: "동사", difficulty: "low", topic: "jlpt_n5" },
  { word: "読む (よむ)", meaning: ["읽다"], partOfSpeech: "동사", difficulty: "low", topic: "jlpt_n5" },
  { word: "書く (かく)", meaning: ["쓰다", "적다"], partOfSpeech: "동사", difficulty: "low", topic: "jlpt_n5" },
  { word: "買う (かう)", meaning: ["사다", "구매하다"], partOfSpeech: "동사", difficulty: "low", topic: "jlpt_n5" },
  { word: "行く (いく)", meaning: ["가다"], partOfSpeech: "동사", difficulty: "low", topic: "jlpt_n5" },
  { word: "来る (くる)", meaning: ["오다"], partOfSpeech: "동사", difficulty: "low", topic: "jlpt_n5" },
  { word: "帰る (かえる)", meaning: ["돌아가다", "귀가하다"], partOfSpeech: "동사", difficulty: "low", topic: "jlpt_n5" },
  { word: "会う (あう)", meaning: ["만나다"], partOfSpeech: "동사", difficulty: "low", topic: "jlpt_n5" },
  { word: "待つ (まつ)", meaning: ["기다리다"], partOfSpeech: "동사", difficulty: "low", topic: "jlpt_n5" },
  { word: "大きい (おおきい)", meaning: ["크다"], partOfSpeech: "형용사", difficulty: "low", topic: "jlpt_n5" },
  { word: "小さい (ちいさい)", meaning: ["작다"], partOfSpeech: "형용사", difficulty: "low", topic: "jlpt_n5" },
  { word: "高い (たかい)", meaning: ["높다", "비싸다"], partOfSpeech: "형용사", difficulty: "low", topic: "jlpt_n5" },
  { word: "安い (やすい)", meaning: ["싸다", "저렴하다"], partOfSpeech: "형용사", difficulty: "low", topic: "jlpt_n5" },
  { word: "新しい (あたらしい)", meaning: ["새롭다"], partOfSpeech: "형용사", difficulty: "low", topic: "jlpt_n5" },
  { word: "古い (ふるい)", meaning: ["오래되다", "낡다"], partOfSpeech: "형용사", difficulty: "low", topic: "jlpt_n5" },
  { word: "良い (いい)", meaning: ["좋다", "착하다"], partOfSpeech: "형용사", difficulty: "low", topic: "jlpt_n5" },
  { word: "近い (ちかい)", meaning: ["가깝다"], partOfSpeech: "형용사", difficulty: "low", topic: "jlpt_n5" },
  { word: "遠い (とおい)", meaning: ["멀다"], partOfSpeech: "형용사", difficulty: "low", topic: "jlpt_n5" },
  { word: "暑い (あつい)", meaning: ["덥다 (날씨)"], partOfSpeech: "형용사", difficulty: "low", topic: "jlpt_n5" },
  { word: "寒い (さむい)", meaning: ["춥다 (날씨)"], partOfSpeech: "형용사", difficulty: "low", topic: "jlpt_n5" },
  { word: "親切 (しんせつ)", meaning: ["친절함"], partOfSpeech: "형용사", difficulty: "low", topic: "jlpt_n5" },
  { word: "必要 (ひつよう)", meaning: ["필요함"], partOfSpeech: "형용사", difficulty: "low", topic: "jlpt_n5" },
  { word: "危険 (きけん)", meaning: ["위험함"], partOfSpeech: "형용사", difficulty: "low", topic: "jlpt_n5" },
  { word: "計画 (けいかく)", meaning: ["계획"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "社会 (しゃかい)", meaning: ["사회"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "文化 (ぶんか)", meaning: ["문화"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "季節 (きせつ)", meaning: ["계절"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "台風 (たいふう)", meaning: ["태풍"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "事故 (じこ)", meaning: ["사고"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "警察 (けいさつ)", meaning: ["경찰"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "運動 (うんどう)", meaning: ["운동"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "授業 (じゅぎょう)", meaning: ["수업"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "試験 (しけん)", meaning: ["시험"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "宿題 (しゅくだい)", meaning: ["숙제"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" },
  { word: "留学 (りゅうがく)", meaning: ["유학"], partOfSpeech: "명사", difficulty: "low", topic: "jlpt_n5" }
];

// 3. 🥈 N4: JLPT N4 공식 빈출 어휘 (일상 회화 및 중급 진입 한자 어휘)
const n4Words = [
  { word: "約束 (やくそく)", meaning: ["약속"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "準備 (じゅんび)", meaning: ["준비"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "経験 (けいけん)", meaning: ["경험"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "失敗 (しっぱい)", meaning: ["실패"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "複雑 (ふくざつ)", meaning: ["복잡함"], partOfSpeech: "형용사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "案内 (あんない)", meaning: ["안내"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "丁寧 (ていねい)", meaning: ["정중함", "공손함"], partOfSpeech: "형용사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "遠慮 (えんりょ)", meaning: ["사양", "조심"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "相談 (そうだん)", meaning: ["상담", "상의"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "連絡 (れんらく)", meaning: ["연락"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "注意 (ちゅうい)", meaning: ["주의", "조심"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "自由 (じゆう)", meaning: ["자유"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "安全 (あんぜん)", meaning: ["안전"], partOfSpeech: "형용사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "理由 (りゆう)", meaning: ["이유"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "興味 (きょうみ)", meaning: ["흥미", "관심"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "習慣 (しゅうかん)", meaning: ["습관"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "技術 (ぎじゅつ)", meaning: ["기술"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "情報 (じょうほう)", meaning: ["정보"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "意見 (いけん)", meaning: ["의견"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "研究 (けんきゅう)", meaning: ["연구"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "経済 (けいざい)", meaning: ["경제"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "政治 (せいじ)", meaning: ["정치"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "法律 (ほうりつ)", meaning: ["법률"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "規則 (きそく)", meaning: ["규칙"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "機会 (きかい)", meaning: ["기회"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "関係 (かんけい)", meaning: ["관계"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "自然 (しぜん)", meaning: ["자연"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "地震 (じしん)", meaning: ["지진"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "交通 (こうつう)", meaning: ["교통"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "健康 (けんこう)", meaning: ["건강"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "休日 (きゅうじつ)", meaning: ["휴일"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "出張 (しゅっちょう)", meaning: ["출장"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "残業 (ざんぎょう)", meaning: ["야근", "잔업"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "給料 (きゅうりょう)", meaning: ["월급", "급여"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "合格 (ごうかく)", meaning: ["합격"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "成績 (せいせき)", meaning: ["성적"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "復習 (ふくしゅう)", meaning: ["복습"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "予習 (よしゅう)", meaning: ["예습"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "卒業 (そつぎょう)", meaning: ["졸업"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "入学 (にゅうがく)", meaning: ["입학"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "専門 (せんもん)", meaning: ["전문"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "論文 (ろんぶん)", meaning: ["논문"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "講義 (こうぎ)", meaning: ["강의"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "会議 (かいぎ)", meaning: ["회의"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "資料 (しりょう)", meaning: ["자료"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "書類 (しょるい)", meaning: ["서류"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "貿易 (ぼうえき)", meaning: ["무역"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "競争 (きょうそう)", meaning: ["경쟁"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "賛成 (さんせい)", meaning: ["찬성"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "比較 (ひかく)", meaning: ["비교"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "重要 (じゅうよう)", meaning: ["중요함"], partOfSpeech: "형용사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "出発 (しゅっぱつ)", meaning: ["출발"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "到着 (とうちゃく)", meaning: ["도착"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "予約 (よやく)", meaning: ["예약"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "説明 (せつめい)", meaning: ["설명"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "質問 (しつもん)", meaning: ["질문"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "趣味 (しゅみ)", meaning: ["취미"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "生活 (せいかつ)", meaning: ["생활"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "空港 (くうこう)", meaning: ["공항"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "住所 (じゅうしょ)", meaning: ["주소"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "乗り換え (のりかえ)", meaning: ["환승", "갈아타기"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "利用 (りよう)", meaning: ["이용", "활용"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "紹介 (しょうかい)", meaning: ["소개"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "用意 (ようい)", meaning: ["준비", "마련"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" },
  { word: "招待 (しょうたい)", meaning: ["초대"], partOfSpeech: "명사", difficulty: "medium", topic: "jlpt_n4" }
];

// 4. 🥇 N3: JLPT N3 공식 빈출 어휘 (비즈니스, 사회, 추상 개념 한자 어휘)
const n3Words = [
  { word: "感謝 (かんしゃ)", meaning: ["감사", "고마움"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "成功 (せいこう)", meaning: ["성공"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "単純 (たんじゅん)", meaning: ["단순함"], partOfSpeech: "형용사", difficulty: "high", topic: "jlpt_n3" },
  { word: "努力 (どりょく)", meaning: ["노력"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "推薦 (すいせん)", meaning: ["추천"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "尊敬 (そんけい)", meaning: ["존경"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "満足 (まんぞく)", meaning: ["만족"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "緊張 (きんちょう)", meaning: ["긴장"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "決定 (けってい)", meaning: ["결정"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "解決 (かいけつ)", meaning: ["해결"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "発表 (はっぴょう)", meaning: ["발표"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "参加 (さんか)", meaning: ["참가"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "確認 (かくにん)", meaning: ["확인"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "想像 (そうぞう)", meaning: ["상상"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "期待 (きたい)", meaning: ["기대"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "整理 (せいり)", meaning: ["정리"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "責任 (せきにん)", meaning: ["책임"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "原因 (げんいん)", meaning: ["원인"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "結果 (けっか)", meaning: ["결과"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "目的 (もくてき)", meaning: ["목적"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "目標 (もくひょう)", meaning: ["목표"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "変化 (へんか)", meaning: ["변화"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "影響 (えいきょう)", meaning: ["영향"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "効果 (こうか)", meaning: ["효과"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "伝統 (でんとう)", meaning: ["전통"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "知識 (ちしき)", meaning: ["지식"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "感情 (かんじょう)", meaning: ["감정"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "表情 (ひょうじょう)", meaning: ["표정"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "態度 (たいど)", meaning: ["태도"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "行動 (こうどう)", meaning: ["행동"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "表現 (ひょうげん)", meaning: ["표현"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "調査 (ちょうさ)", meaning: ["조사"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "発見 (はっけん)", meaning: ["발견"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "発明 (はつめい)", meaning: ["발명"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "発達 (はったつ)", meaning: ["발달"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "条件 (じょうけん)", meaning: ["조건"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "状況 (じょうきょう)", meaning: ["상황"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "環境 (かんきょう)", meaning: ["환경"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "気候 (きこう)", meaning: ["기후"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "事件 (じけん)", meaning: ["사건"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "犯罪 (はんざい)", meaning: ["범죄"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "治療 (ちりょう)", meaning: ["치료"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "手術 (しゅじゅつ)", meaning: ["수술"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "体調 (たいちょう)", meaning: ["몸 상태", "컨디션"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "栄養 (えいよう)", meaning: ["영양"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "睡眠 (すいみん)", meaning: ["수면"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "休憩 (きゅうけい)", meaning: ["휴식", "쉬는 시간"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "休暇 (きゅうか)", meaning: ["휴가"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "面接 (めんせつ)", meaning: ["면접"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "履歴書 (りれきしょ)", meaning: ["이력서"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "不合格 (ふごうかく)", meaning: ["불합격"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "専攻 (せんこう)", meaning: ["전공"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "講演 (こうえん)", meaning: ["강연"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "契約 (けいやく)", meaning: ["계약"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "取引 (とりひき)", meaning: ["거래"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "交渉 (こうしょう)", meaning: ["교섭", "협상"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "協力 (きょうりょく)", meaning: ["협력"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "支持 (しじ)", meaning: ["지지", "후원"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "批判 (ひはん)", meaning: ["비판"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "評価 (ひょうか)", meaning: ["평가"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "基準 (きじゅん)", meaning: ["기준"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "標準 (ひょうじゅん)", meaning: ["표준"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "割合 (わりあい)", meaning: ["비율"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "平均 (へいきん)", meaning: ["평균"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "増加 (ぞうか)", meaning: ["증가"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "減少 (げんしょう)", meaning: ["감소"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "発展 (はってん)", meaning: ["발전"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "改善 (かいぜん)", meaning: ["개선"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "改革 (かいかく)", meaning: ["개혁"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "維持 (いじ)", meaning: ["유지"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "保護 (ほご)", meaning: ["보호"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "防止 (ぼうし)", meaning: ["방지"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "予防 (よぼう)", meaning: ["예방"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "対策 (たいさく)", meaning: ["대책"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "方針 (ほうしん)", meaning: ["방침"], partOfSpeech: "명사", difficulty: "high", topic: "jlpt_n3" },
  { word: "誠実 (せいじつ)", meaning: ["성실함"], partOfSpeech: "형용사", difficulty: "high", topic: "jlpt_n3" },
  { word: "冷静 (れいせい)", meaning: ["침착함", "냉정함"], partOfSpeech: "형용사", difficulty: "high", topic: "jlpt_n3" },
  { word: "勇敢 (ゆうかん)", meaning: ["용감함"], partOfSpeech: "형용사", difficulty: "high", topic: "jlpt_n3" },
  { word: "頑固 (がんこ)", meaning: ["완고함", "고집스러움"], partOfSpeech: "형용사", difficulty: "high", topic: "jlpt_n3" },
  { word: "柔軟 (じゅうなん)", meaning: ["유연함"], partOfSpeech: "형용사", difficulty: "high", topic: "jlpt_n3" },
  { word: "正確 (せいかく)", meaning: ["정확함"], partOfSpeech: "형용사", difficulty: "high", topic: "jlpt_n3" },
  { word: "適切 (てきせつ)", meaning: ["적절함"], partOfSpeech: "형용사", difficulty: "high", topic: "jlpt_n3" },
  { word: "妥当 (だとう)", meaning: ["타당함"], partOfSpeech: "형용사", difficulty: "high", topic: "jlpt_n3" },
  { word: "深刻 (しんこく)", meaning: ["심각함"], partOfSpeech: "형용사", difficulty: "high", topic: "jlpt_n3" },
  { word: "貴重 (きちょう)", meaning: ["귀중함"], partOfSpeech: "형용사", difficulty: "high", topic: "jlpt_n3" }
];

// 전체 시험용 어휘 결합 (중복 방지)
const seenWords = new Set();
const combinedExamWords = [];

for (const item of [...basicWords, ...n5Words, ...n4Words, ...n3Words]) {
  const norm = item.word.replace(/\s+/g, '');
  if (!seenWords.has(norm)) {
    seenWords.add(norm);
    combinedExamWords.push(item);
  }
}

// 생활일본어 데이터 (기존 160단어 유지)
const lifeWords = [
  { word: "お会計 (おかいけい)", meaning: ["계산", "식당 계산"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "おすすめ", meaning: ["추천 메뉴", "추천"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "持ち帰り (もちかえり)", meaning: ["포장", "테이크아웃"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "店内 (てんない)", meaning: ["매장 내 식사"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "お冷 (おひや)", meaning: ["찬물 (식당 무료 물)"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "大盛り (おおもり)", meaning: ["곱배기", "양 많이"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "少なめ (すくなめ)", meaning: ["양 적게"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "おかわり", meaning: ["리필", "한 그릇 더"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "別々 (べつべつ)", meaning: ["각자 따로 계산"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "一緒 (いっしょ)", meaning: ["함께 합산 계산"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "注文 (ちゅうもん)", meaning: ["주문"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "居酒屋 (いざかや)", meaning: ["일본식 주점", "이자카야"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "飲み放題 (のみほうだい)", meaning: ["음료 및 주류 무제한"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "食べ放題 (たべほうだい)", meaning: ["식사 및 안주 뷔페 무제한"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "乾杯 (かんぱい)", meaning: ["건배"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "領収書 (りょうしゅうしょ)", meaning: ["영수증"], partOfSpeech: "명사", difficulty: "medium", topic: "shopping" },
  { word: "レシート", meaning: ["구매 영수증"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "袋 (ふくろ)", meaning: ["비닐봉투", "쇼핑백"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "免税 (めんぜい)", meaning: ["면세"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "パスポート", meaning: ["여권"], partOfSpeech: "명사", difficulty: "low", topic: "travel" },
  { word: "現金 (げんきん)", meaning: ["현금"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "クレジットカード", meaning: ["신용카드"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "電子マネー", meaning: ["전자화폐", "교통카드 페이"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "売り切れ (うりきれ)", meaning: ["품절", "매진"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "割引 (わりびき)", meaning: ["할인"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "半額 (はんがく)", meaning: ["반값", "50% 할인"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "税込み (ぜいこみ)", meaning: ["세금 포함"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "税抜き (ぜいぬき)", meaning: ["세금 별도"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "試着 (しちゃく)", meaning: ["옷 입어보기", "시착"], partOfSpeech: "명사", difficulty: "medium", topic: "shopping" },
  { word: "試食 (ししょく)", meaning: ["음식 맛보기", "시식"], partOfSpeech: "명사", difficulty: "medium", topic: "shopping" },
  { word: "新商品 (しんしょうひん)", meaning: ["신상품"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "限定 (げんてい)", meaning: ["한정 판매", "기간 한정"], partOfSpeech: "명사", difficulty: "medium", topic: "shopping" },
  { word: "定休日 (ていきゅうび)", meaning: ["정기 휴일"], partOfSpeech: "명사", difficulty: "medium", topic: "shopping" },
  { word: "営業時間 (えいぎょうじかん)", meaning: ["영업 시간"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "満席 (まんせき)", meaning: ["만석", "빈자리 없음"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "空席 (くうせき)", meaning: ["빈자리", "공석"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "禁煙 (きんえん)", meaning: ["금연"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "喫煙 (きつえん)", meaning: ["흡연"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "切符 (きっぷ)", meaning: ["승차권", "표"], partOfSpeech: "명사", difficulty: "low", topic: "traffic" },
  { word: "運賃 (うんちん)", meaning: ["교통 운임", "차비"], partOfSpeech: "명사", difficulty: "medium", topic: "traffic" },
  { word: "改札口 (かいさつぐち)", meaning: ["지하철 개찰구"], partOfSpeech: "명사", difficulty: "low", topic: "traffic" },
  { word: "出口 (でぐち)", meaning: ["출구"], partOfSpeech: "명사", difficulty: "low", topic: "traffic" },
  { word: "入口 (いりぐち)", meaning: ["입구"], partOfSpeech: "명사", difficulty: "low", topic: "traffic" },
  { word: "乗り場 (のりば)", meaning: ["타는 곳", "승강장"], partOfSpeech: "명사", difficulty: "low", topic: "traffic" },
  { word: "乗り換え (のりかえ)", meaning: ["환승", "갈아타기"], partOfSpeech: "명사", difficulty: "low", topic: "traffic" },
  { word: "終電 (しゅうでん)", meaning: ["막차 전철"], partOfSpeech: "명사", difficulty: "low", topic: "traffic" },
  { word: "始発 (しはつ)", meaning: ["첫차"], partOfSpeech: "명사", difficulty: "low", topic: "traffic" },
  { word: "各駅停車 (かくえきていしゃ)", meaning: ["각역 정차 보통열차"], partOfSpeech: "명사", difficulty: "medium", topic: "traffic" },
  { word: "快速 (かいそく)", meaning: ["쾌속 열차"], partOfSpeech: "명사", difficulty: "low", topic: "traffic" },
  { word: "特急 (とっきゅう)", meaning: ["특급 열차"], partOfSpeech: "명사", difficulty: "low", topic: "traffic" },
  { word: "指定席 (していせき)", meaning: ["예약 지정석"], partOfSpeech: "명사", difficulty: "medium", topic: "traffic" },
  { word: "自由席 (じゆうせき)", meaning: ["자유석"], partOfSpeech: "명사", difficulty: "low", topic: "traffic" },
  { word: "優先席 (ゆうせんせき)", meaning: ["노약자석", "교통약자석"], partOfSpeech: "명사", difficulty: "medium", topic: "traffic" },
  { word: "遅延 (ちえん)", meaning: ["열차 지연", "연착"], partOfSpeech: "명사", difficulty: "medium", topic: "traffic" },
  { word: "運休 (うんきゅう)", meaning: ["운행 중단"], partOfSpeech: "명사", difficulty: "medium", topic: "traffic" },
  { word: "踏切 (ふみきり)", meaning: ["철길 건널목"], partOfSpeech: "명사", difficulty: "medium", topic: "traffic" },
  { word: "バス停 (ばすてい)", meaning: ["버스 정류장"], partOfSpeech: "명사", difficulty: "low", topic: "traffic" },
  { word: "タクシー乗り場 (たくしーのりば)", meaning: ["택시 승강장"], partOfSpeech: "명사", difficulty: "low", topic: "traffic" },
  { word: "荷物 (にもつ)", meaning: ["여행 짐", "수하물"], partOfSpeech: "명사", difficulty: "low", topic: "travel" },
  { word: "コインロッカー", meaning: ["코인 라커", "물품 보관함"], partOfSpeech: "명사", difficulty: "low", topic: "travel" },
  { word: "預かり所 (あずかりじょ)", meaning: ["수하물 보관소"], partOfSpeech: "명사", difficulty: "medium", topic: "travel" },
  { word: "忘れ物 (わすれもの)", meaning: ["두고 온 물건", "분실물"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "落とし物 (おとしもの)", meaning: ["떨어뜨린 물건", "유실물"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "交番 (こうばん)", meaning: ["파출소"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "案内所 (あんないじょ)", meaning: ["관광 안내소"], partOfSpeech: "명사", difficulty: "low", topic: "travel" },
  { word: "両替 (りょうがえ)", meaning: ["환전"], partOfSpeech: "명사", difficulty: "low", topic: "travel" },
  { word: "為替レート (かわせれーと)", meaning: ["환율"], partOfSpeech: "명사", difficulty: "medium", topic: "travel" },
  { word: "ATM", meaning: ["현금자동입출금기"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "手数料 (てすうりょう)", meaning: ["수수료"], partOfSpeech: "명사", difficulty: "medium", topic: "shopping" },
  { word: "チェックイン", meaning: ["호텔 체크인"], partOfSpeech: "명사", difficulty: "low", topic: "hotel" },
  { word: "チェックアウト", meaning: ["호텔 체크아웃"], partOfSpeech: "명사", difficulty: "low", topic: "hotel" },
  { word: "予約 (よやく)", meaning: ["예약"], partOfSpeech: "명사", difficulty: "low", topic: "hotel" },
  { word: "宿泊 (しゅくはく)", meaning: ["숙박"], partOfSpeech: "명사", difficulty: "medium", topic: "hotel" },
  { word: "部屋 (へや)", meaning: ["객실", "방"], partOfSpeech: "명사", difficulty: "low", topic: "hotel" },
  { word: "鍵 (かぎ)", meaning: ["객실 열쇠", "카드키"], partOfSpeech: "명사", difficulty: "low", topic: "hotel" },
  { word: "フロント", meaning: ["호텔 프런트 데스크"], partOfSpeech: "명사", difficulty: "low", topic: "hotel" },
  { word: "朝食 (ちょうしょく)", meaning: ["아침 식사 조식"], partOfSpeech: "명사", difficulty: "low", topic: "hotel" },
  { word: "夕食 (ゆうしょく)", meaning: ["저녁 식사 석식"], partOfSpeech: "명사", difficulty: "low", topic: "hotel" },
  { word: "温泉 (おんせん)", meaning: ["온천"], partOfSpeech: "명사", difficulty: "low", topic: "travel" },
  { word: "露天風呂 (ろてんぶろ)", meaning: ["야외 노천탕"], partOfSpeech: "명사", difficulty: "medium", topic: "travel" },
  { word: "浴衣 (ゆかた)", meaning: ["유카타 실내 가운"], partOfSpeech: "명사", difficulty: "low", topic: "hotel" },
  { word: "アメニティ", meaning: ["어메니티 세면도구"], partOfSpeech: "명사", difficulty: "low", topic: "hotel" },
  { word: "タオル", meaning: ["수건 타월"], partOfSpeech: "명사", difficulty: "low", topic: "hotel" },
  { word: "ドライヤー", meaning: ["헤어 드라이어"], partOfSpeech: "명사", difficulty: "low", topic: "hotel" },
  { word: "Wi-Fi (わいふぁい)", meaning: ["무선 인터넷 와이파이"], partOfSpeech: "명사", difficulty: "low", topic: "hotel" },
  { word: "パスワード", meaning: ["접속 비밀번호"], partOfSpeech: "명사", difficulty: "low", topic: "hotel" },
  { word: "充電器 (じゅうでんき)", meaning: ["스마트폰 충전기"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "コンセント", meaning: ["전원 콘센트"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "変圧器 (へんあつき)", meaning: ["변압기 돼지코 플러그"], partOfSpeech: "명사", difficulty: "medium", topic: "travel" },
  { word: "トイレ", meaning: ["화장실"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "化粧室 (けしょうしつ)", meaning: ["정중한 화장실 파우더룸"], partOfSpeech: "명사", difficulty: "medium", topic: "life" },
  { word: "非常口 (ひじょうぐち)", meaning: ["비상구"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "避難所 (ひなんじょ)", meaning: ["재난 대피소"], partOfSpeech: "명사", difficulty: "medium", topic: "life" },
  { word: "救急車 (きゅうきゅうしゃ)", meaning: ["구급차"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "消防車 (しょうぼうしゃ)", meaning: ["소방차"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "薬局 (やっきょく)", meaning: ["약국"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "処方箋 (しょほうせん)", meaning: ["병원 처방전"], partOfSpeech: "명사", difficulty: "medium", topic: "life" },
  { word: "鎮痛剤 (ちんつうざい)", meaning: ["통증 완화 진통제"], partOfSpeech: "명사", difficulty: "medium", topic: "life" },
  { word: "風邪薬 (かぜぐすり)", meaning: ["감기약"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "胃腸薬 (いちょうやく)", meaning: ["소화제 위장약"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "絆創膏 (ばんそうこう)", meaning: ["상처 반창고"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "頭痛 (ずつう)", meaning: ["머리 통증 두통"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "腹痛 (ふくつう)", meaning: ["배탈 복통"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "発熱 (はつねつ)", meaning: ["체온 상승 발열"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "吐き気 (はきけ)", meaning: ["메스꺼움 구토감"], partOfSpeech: "명사", difficulty: "medium", topic: "life" },
  { word: "めまい", meaning: ["어지러움 현기증"], partOfSpeech: "명사", difficulty: "medium", topic: "life" },
  { word: "診察 (しんさつ)", meaning: ["의사 진찰 진료"], partOfSpeech: "명사", difficulty: "medium", topic: "life" },
  { word: "保険証 (ほけんしょう)", meaning: ["건강보험증"], partOfSpeech: "명사", difficulty: "low", topic: "life" },
  { word: "コンビニ", meaning: ["편의점"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "おにぎり", meaning: ["삼각김밥 주먹밥"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "お弁当 (おべんとう)", meaning: ["편의점 도시락"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "温め (あたため)", meaning: ["전자레인지 데우기"], partOfSpeech: "명사", difficulty: "low", topic: "shopping" },
  { word: "箸 (はし)", meaning: ["식사용 젓가락"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "スプーン", meaning: ["숟가락 스푼"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "フォーク", meaning: ["포크"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "ストロー", meaning: ["음료 빨대"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "おしぼり", meaning: ["물티슈 물수건"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "水 (みず)", meaning: ["마시는 물"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "お茶 (おちゃ)", meaning: ["녹차 차 음료"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "氷 (こおり)", meaning: ["시원한 얼음"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "生ビール (なまびーる)", meaning: ["생맥주"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "ハイボール", meaning: ["위스키 하이볼"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "日本酒 (にほんしゅ)", meaning: ["일본 전통주 사케"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "焼酎 (しょうちゅう)", meaning: ["소주"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "つまみ", meaning: ["술안주"], partOfSpeech: "명사", difficulty: "low", topic: "restaurant" },
  { word: "お通し (おとおし)", meaning: ["기본 자릿세 안주"], partOfSpeech: "명사", difficulty: "medium", topic: "restaurant" },
  { word: "辛い (からい)", meaning: ["매운 맛"], partOfSpeech: "형용사", difficulty: "low", topic: "restaurant" },
  { word: "甘い (あまい)", meaning: ["단 맛 달콤함"], partOfSpeech: "형용사", difficulty: "low", topic: "restaurant" },
  { word: "しょっぱい", meaning: ["짠 맛 짭짤함"], partOfSpeech: "형용사", difficulty: "low", topic: "restaurant" },
  { word: "酸っぱい (すっぱい)", meaning: ["새콤한 신 맛"], partOfSpeech: "형용사", difficulty: "low", topic: "restaurant" },
  { word: "苦い (にがい)", meaning: ["쓴 맛"], partOfSpeech: "형용사", difficulty: "medium", topic: "restaurant" },
  { word: "熱い (あつい)", meaning: ["뜨거운 온도"], partOfSpeech: "형용사", difficulty: "low", topic: "restaurant" },
  { word: "冷たい (つめたい)", meaning: ["차가운 온도"], partOfSpeech: "형용사", difficulty: "low", topic: "restaurant" },
  { word: "美味しい (おいしい)", meaning: ["맛있다 맛좋음"], partOfSpeech: "형용사", difficulty: "low", topic: "restaurant" },
  { word: "まずい", meaning: ["맛없다"], partOfSpeech: "형용사", difficulty: "low", topic: "restaurant" },
  { word: "お腹が空いた (おなかがすいた)", meaning: ["배가 고프다"], partOfSpeech: "표현", difficulty: "low", topic: "life" },
  { word: "お腹がいっぱい (おなかがいっぱい)", meaning: ["배가 부르다"], partOfSpeech: "표현", difficulty: "low", topic: "life" },
  { word: "喉が渇いた (のどがかわいた)", meaning: ["목이 마르다"], partOfSpeech: "표현", difficulty: "low", topic: "life" },
  { word: "すみません", meaning: ["저기요 실례합니다 죄송합니다"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "ありがとうございます", meaning: ["대단히 감사합니다"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "どういたしまして", meaning: ["별말씀을요 천만에요"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "ごめんなさい", meaning: ["미안합니다 죄송해요"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "失礼します (しつれいします)", meaning: ["실례하겠습니다"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "大丈夫 (だいじょうぶ)", meaning: ["괜찮음 문제없음"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "ちょっと待ってください", meaning: ["잠시만 기다려주세요"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "いくらですか", meaning: ["가격이 얼마입니까?"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "これをください", meaning: ["이것으로 주세요"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "どこですか", meaning: ["위치가 어디입니까?"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "助けてください (たすけてください)", meaning: ["도와주세요 살려주세요"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "写真を撮ってもいいですか", meaning: ["사진을 찍어도 됩니까?"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "英語が話せますか", meaning: ["영어를 할 수 있습니까?"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "韓国語のメニューはありますか", meaning: ["한국어 메뉴판 있습니까?"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "Wi-Fiはありますか", meaning: ["와이파이 있습니까?"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "カードは使えますか", meaning: ["신용카드 결제 됩니까?"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "迷子になりました (まいごになりました)", meaning: ["길을 잃어버렸습니다"], partOfSpeech: "표현", difficulty: "medium", topic: "conversation" },
  { word: "いらっしゃいませ", meaning: ["어서 오세요 매장 인사"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "かしこまりました", meaning: ["잘 알겠습니다 정중한 승낙"], partOfSpeech: "표현", difficulty: "medium", topic: "conversation" },
  { word: "少々お待ちください (しょうしょうおまちください)", meaning: ["잠시만 기다려 주십시오 점원 경어"], partOfSpeech: "표현", difficulty: "medium", topic: "conversation" },
  { word: "お待たせしました", meaning: ["오래 기다리셨습니다 음식 서빙 인사"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" },
  { word: "気をつけて (きをつけて)", meaning: ["조심해서 가세요 안녕히 가세요"], partOfSpeech: "표현", difficulty: "low", topic: "conversation" }
];

function buildDatabase(name, category, description, wordList) {
  const formattedWords = wordList.map((item, idx) => ({
    id: idx + 1,
    word: item.word,
    partOfSpeech: item.partOfSpeech,
    meaning: item.meaning,
    difficulty: item.difficulty,
    topic: item.topic
  }));

  return {
    databaseVersion: 2,
    name,
    category,
    description,
    wordCount: formattedWords.length,
    words: formattedWords
  };
}

const examDb = buildDatabase(
  "일본어 자격증 및 기초 (기초 / N5 / N4 / N3 등급별 어휘집)",
  "japanese_exam",
  "일본어 기초 및 JLPT N5~N3 등급별 빈출 핵심 어휘 수록 (히라가나/뜻 맞추기 완비)",
  combinedExamWords
);

const lifeDb = buildDatabase(
  "완전 생활일본어 (여행·식당·교통·호텔·쇼핑 실전 회화 어휘)",
  "japanese_life",
  "일본 여행 및 일상생활 생존 필수 실전 어휘 수록",
  lifeWords
);

const targetDir = path.join(__dirname, '..', 'public', 'data');
fs.writeFileSync(path.join(targetDir, 'builtin_japanese_exam.json'), JSON.stringify(examDb, null, 2), 'utf-8');
fs.writeFileSync(path.join(targetDir, 'builtin_japanese_life.json'), JSON.stringify(lifeDb, null, 2), 'utf-8');

console.log(`Generated builtin_japanese_exam.json with ${combinedExamWords.length} words (Basic: ${basicWords.length}, N5: ${n5Words.length}, N4: ${n4Words.length}, N3: ${n3Words.length}).`);
console.log(`Generated builtin_japanese_life.json with ${lifeWords.length} words.`);
